// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AddIntroducerOwnerRequest v1 add introducer owner request
// swagger:model v1AddIntroducerOwnerRequest
type V1AddIntroducerOwnerRequest struct {

	// account id
	AccountID string `json:"account_id,omitempty"`

	// introducer id
	IntroducerID string `json:"introducer_id,omitempty"`
}

// Validate validates this v1 add introducer owner request
func (m *V1AddIntroducerOwnerRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AddIntroducerOwnerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AddIntroducerOwnerRequest) UnmarshalBinary(b []byte) error {
	var res V1AddIntroducerOwnerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
