// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1GetIntroducerResponse v1 get introducer response
// swagger:model v1GetIntroducerResponse
type V1GetIntroducerResponse struct {

	// introducer
	Introducer *V1Introducer `json:"introducer,omitempty"`
}

// Validate validates this v1 get introducer response
func (m *V1GetIntroducerResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIntroducer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetIntroducerResponse) validateIntroducer(formats strfmt.Registry) error {

	if swag.IsZero(m.Introducer) { // not required
		return nil
	}

	if m.Introducer != nil {
		if err := m.Introducer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("introducer")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1GetIntroducerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetIntroducerResponse) UnmarshalBinary(b []byte) error {
	var res V1GetIntroducerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
