// Code generated by go-swagger; DO NOT EDIT.

package domain_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/domainconfig/models"
)

// ResolveReader is a Reader for the Resolve structure.
type ResolveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResolveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResolveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewResolveOK creates a ResolveOK with default headers values
func NewResolveOK() *ResolveOK {
	return &ResolveOK{}
}

/*ResolveOK handles this case with default header values.

A successful response.
*/
type ResolveOK struct {
	Payload *models.V1ResolveResponse
}

func (o *ResolveOK) Error() string {
	return fmt.Sprintf("[GET /v1/resolve/{domain_name}][%d] resolveOK  %+v", 200, o.Payload)
}

func (o *ResolveOK) GetPayload() *models.V1ResolveResponse {
	return o.Payload
}

func (o *ResolveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ResolveResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
