// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewCreateOrganisationParams creates a new CreateOrganisationParams object
// with the default values initialized.
func NewCreateOrganisationParams() *CreateOrganisationParams {
	var ()
	return &CreateOrganisationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOrganisationParamsWithTimeout creates a new CreateOrganisationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateOrganisationParamsWithTimeout(timeout time.Duration) *CreateOrganisationParams {
	var ()
	return &CreateOrganisationParams{

		timeout: timeout,
	}
}

// NewCreateOrganisationParamsWithContext creates a new CreateOrganisationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateOrganisationParamsWithContext(ctx context.Context) *CreateOrganisationParams {
	var ()
	return &CreateOrganisationParams{

		Context: ctx,
	}
}

// NewCreateOrganisationParamsWithHTTPClient creates a new CreateOrganisationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateOrganisationParamsWithHTTPClient(client *http.Client) *CreateOrganisationParams {
	var ()
	return &CreateOrganisationParams{
		HTTPClient: client,
	}
}

/*CreateOrganisationParams contains all the parameters to send to the API endpoint
for the create organisation operation typically these are written to a http.Request
*/
type CreateOrganisationParams struct {

	/*Body*/
	Body *models.V1CreateOrganisationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create organisation params
func (o *CreateOrganisationParams) WithTimeout(timeout time.Duration) *CreateOrganisationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create organisation params
func (o *CreateOrganisationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create organisation params
func (o *CreateOrganisationParams) WithContext(ctx context.Context) *CreateOrganisationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create organisation params
func (o *CreateOrganisationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create organisation params
func (o *CreateOrganisationParams) WithHTTPClient(client *http.Client) *CreateOrganisationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create organisation params
func (o *CreateOrganisationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create organisation params
func (o *CreateOrganisationParams) WithBody(body *models.V1CreateOrganisationRequest) *CreateOrganisationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create organisation params
func (o *CreateOrganisationParams) SetBody(body *models.V1CreateOrganisationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOrganisationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
