// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// CreateOrganisationReader is a Reader for the CreateOrganisation structure.
type CreateOrganisationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrganisationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOrganisationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateOrganisationOK creates a CreateOrganisationOK with default headers values
func NewCreateOrganisationOK() *CreateOrganisationOK {
	return &CreateOrganisationOK{}
}

/*CreateOrganisationOK handles this case with default header values.

A successful response.
*/
type CreateOrganisationOK struct {
	Payload models.V1CreateOrganisationResponse
}

func (o *CreateOrganisationOK) Error() string {
	return fmt.Sprintf("[POST /v1/organisations][%d] createOrganisationOK  %+v", 200, o.Payload)
}

func (o *CreateOrganisationOK) GetPayload() models.V1CreateOrganisationResponse {
	return o.Payload
}

func (o *CreateOrganisationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
