// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewIdentitiesLoginParams creates a new IdentitiesLoginParams object
// with the default values initialized.
func NewIdentitiesLoginParams() *IdentitiesLoginParams {
	var ()
	return &IdentitiesLoginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIdentitiesLoginParamsWithTimeout creates a new IdentitiesLoginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIdentitiesLoginParamsWithTimeout(timeout time.Duration) *IdentitiesLoginParams {
	var ()
	return &IdentitiesLoginParams{

		timeout: timeout,
	}
}

// NewIdentitiesLoginParamsWithContext creates a new IdentitiesLoginParams object
// with the default values initialized, and the ability to set a context for a request
func NewIdentitiesLoginParamsWithContext(ctx context.Context) *IdentitiesLoginParams {
	var ()
	return &IdentitiesLoginParams{

		Context: ctx,
	}
}

// NewIdentitiesLoginParamsWithHTTPClient creates a new IdentitiesLoginParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIdentitiesLoginParamsWithHTTPClient(client *http.Client) *IdentitiesLoginParams {
	var ()
	return &IdentitiesLoginParams{
		HTTPClient: client,
	}
}

/*IdentitiesLoginParams contains all the parameters to send to the API endpoint
for the identities login operation typically these are written to a http.Request
*/
type IdentitiesLoginParams struct {

	/*Body*/
	Body *models.V1LoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the identities login params
func (o *IdentitiesLoginParams) WithTimeout(timeout time.Duration) *IdentitiesLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the identities login params
func (o *IdentitiesLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the identities login params
func (o *IdentitiesLoginParams) WithContext(ctx context.Context) *IdentitiesLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the identities login params
func (o *IdentitiesLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the identities login params
func (o *IdentitiesLoginParams) WithHTTPClient(client *http.Client) *IdentitiesLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the identities login params
func (o *IdentitiesLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the identities login params
func (o *IdentitiesLoginParams) WithBody(body *models.V1LoginRequest) *IdentitiesLoginParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the identities login params
func (o *IdentitiesLoginParams) SetBody(body *models.V1LoginRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IdentitiesLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
