// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// IdentitiesQueryOrganisationsReader is a Reader for the IdentitiesQueryOrganisations structure.
type IdentitiesQueryOrganisationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesQueryOrganisationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesQueryOrganisationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesQueryOrganisationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesQueryOrganisationsOK creates a IdentitiesQueryOrganisationsOK with default headers values
func NewIdentitiesQueryOrganisationsOK() *IdentitiesQueryOrganisationsOK {
	return &IdentitiesQueryOrganisationsOK{}
}

/*IdentitiesQueryOrganisationsOK handles this case with default header values.

A successful response.
*/
type IdentitiesQueryOrganisationsOK struct {
	Payload *models.V1QueryOrganisationsResponse
}

func (o *IdentitiesQueryOrganisationsOK) Error() string {
	return fmt.Sprintf("[GET /v1/organisations][%d] identitiesQueryOrganisationsOK  %+v", 200, o.Payload)
}

func (o *IdentitiesQueryOrganisationsOK) GetPayload() *models.V1QueryOrganisationsResponse {
	return o.Payload
}

func (o *IdentitiesQueryOrganisationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1QueryOrganisationsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesQueryOrganisationsDefault creates a IdentitiesQueryOrganisationsDefault with default headers values
func NewIdentitiesQueryOrganisationsDefault(code int) *IdentitiesQueryOrganisationsDefault {
	return &IdentitiesQueryOrganisationsDefault{
		_statusCode: code,
	}
}

/*IdentitiesQueryOrganisationsDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesQueryOrganisationsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities query organisations default response
func (o *IdentitiesQueryOrganisationsDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesQueryOrganisationsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/organisations][%d] Identities_QueryOrganisations default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesQueryOrganisationsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesQueryOrganisationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
