// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// IdentitiesTokenRenewReader is a Reader for the IdentitiesTokenRenew structure.
type IdentitiesTokenRenewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesTokenRenewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesTokenRenewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesTokenRenewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesTokenRenewOK creates a IdentitiesTokenRenewOK with default headers values
func NewIdentitiesTokenRenewOK() *IdentitiesTokenRenewOK {
	return &IdentitiesTokenRenewOK{}
}

/*IdentitiesTokenRenewOK handles this case with default header values.

A successful response.
*/
type IdentitiesTokenRenewOK struct {
	Payload *models.V1TokenRenewResponse
}

func (o *IdentitiesTokenRenewOK) Error() string {
	return fmt.Sprintf("[POST /v1/token/renew][%d] identitiesTokenRenewOK  %+v", 200, o.Payload)
}

func (o *IdentitiesTokenRenewOK) GetPayload() *models.V1TokenRenewResponse {
	return o.Payload
}

func (o *IdentitiesTokenRenewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TokenRenewResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesTokenRenewDefault creates a IdentitiesTokenRenewDefault with default headers values
func NewIdentitiesTokenRenewDefault(code int) *IdentitiesTokenRenewDefault {
	return &IdentitiesTokenRenewDefault{
		_statusCode: code,
	}
}

/*IdentitiesTokenRenewDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesTokenRenewDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities token renew default response
func (o *IdentitiesTokenRenewDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesTokenRenewDefault) Error() string {
	return fmt.Sprintf("[POST /v1/token/renew][%d] Identities_TokenRenew default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesTokenRenewDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesTokenRenewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
