// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIdentitiesQueryAccountMembershipsParams creates a new IdentitiesQueryAccountMembershipsParams object
// with the default values initialized.
func NewIdentitiesQueryAccountMembershipsParams() *IdentitiesQueryAccountMembershipsParams {
	var ()
	return &IdentitiesQueryAccountMembershipsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIdentitiesQueryAccountMembershipsParamsWithTimeout creates a new IdentitiesQueryAccountMembershipsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIdentitiesQueryAccountMembershipsParamsWithTimeout(timeout time.Duration) *IdentitiesQueryAccountMembershipsParams {
	var ()
	return &IdentitiesQueryAccountMembershipsParams{

		timeout: timeout,
	}
}

// NewIdentitiesQueryAccountMembershipsParamsWithContext creates a new IdentitiesQueryAccountMembershipsParams object
// with the default values initialized, and the ability to set a context for a request
func NewIdentitiesQueryAccountMembershipsParamsWithContext(ctx context.Context) *IdentitiesQueryAccountMembershipsParams {
	var ()
	return &IdentitiesQueryAccountMembershipsParams{

		Context: ctx,
	}
}

// NewIdentitiesQueryAccountMembershipsParamsWithHTTPClient creates a new IdentitiesQueryAccountMembershipsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIdentitiesQueryAccountMembershipsParamsWithHTTPClient(client *http.Client) *IdentitiesQueryAccountMembershipsParams {
	var ()
	return &IdentitiesQueryAccountMembershipsParams{
		HTTPClient: client,
	}
}

/*IdentitiesQueryAccountMembershipsParams contains all the parameters to send to the API endpoint
for the identities query account memberships operation typically these are written to a http.Request
*/
type IdentitiesQueryAccountMembershipsParams struct {

	/*AccountID*/
	AccountID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) WithTimeout(timeout time.Duration) *IdentitiesQueryAccountMembershipsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) WithContext(ctx context.Context) *IdentitiesQueryAccountMembershipsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) WithHTTPClient(client *http.Client) *IdentitiesQueryAccountMembershipsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) WithAccountID(accountID *string) *IdentitiesQueryAccountMembershipsParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the identities query account memberships params
func (o *IdentitiesQueryAccountMembershipsParams) SetAccountID(accountID *string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *IdentitiesQueryAccountMembershipsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param account_id
		var qrAccountID string
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := qrAccountID
		if qAccountID != "" {
			if err := r.SetQueryParam("account_id", qAccountID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
