// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// IdentitiesCreateOrganisationReader is a Reader for the IdentitiesCreateOrganisation structure.
type IdentitiesCreateOrganisationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesCreateOrganisationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesCreateOrganisationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesCreateOrganisationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesCreateOrganisationOK creates a IdentitiesCreateOrganisationOK with default headers values
func NewIdentitiesCreateOrganisationOK() *IdentitiesCreateOrganisationOK {
	return &IdentitiesCreateOrganisationOK{}
}

/*IdentitiesCreateOrganisationOK handles this case with default header values.

A successful response.
*/
type IdentitiesCreateOrganisationOK struct {
	Payload models.V1CreateOrganisationResponse
}

func (o *IdentitiesCreateOrganisationOK) Error() string {
	return fmt.Sprintf("[POST /v1/organisations][%d] identitiesCreateOrganisationOK  %+v", 200, o.Payload)
}

func (o *IdentitiesCreateOrganisationOK) GetPayload() models.V1CreateOrganisationResponse {
	return o.Payload
}

func (o *IdentitiesCreateOrganisationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesCreateOrganisationDefault creates a IdentitiesCreateOrganisationDefault with default headers values
func NewIdentitiesCreateOrganisationDefault(code int) *IdentitiesCreateOrganisationDefault {
	return &IdentitiesCreateOrganisationDefault{
		_statusCode: code,
	}
}

/*IdentitiesCreateOrganisationDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesCreateOrganisationDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities create organisation default response
func (o *IdentitiesCreateOrganisationDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesCreateOrganisationDefault) Error() string {
	return fmt.Sprintf("[POST /v1/organisations][%d] Identities_CreateOrganisation default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesCreateOrganisationDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesCreateOrganisationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
