// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// IdentitiesUpdateAccountDetailsReader is a Reader for the IdentitiesUpdateAccountDetails structure.
type IdentitiesUpdateAccountDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesUpdateAccountDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesUpdateAccountDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesUpdateAccountDetailsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesUpdateAccountDetailsOK creates a IdentitiesUpdateAccountDetailsOK with default headers values
func NewIdentitiesUpdateAccountDetailsOK() *IdentitiesUpdateAccountDetailsOK {
	return &IdentitiesUpdateAccountDetailsOK{}
}

/*IdentitiesUpdateAccountDetailsOK handles this case with default header values.

A successful response.
*/
type IdentitiesUpdateAccountDetailsOK struct {
	Payload models.V1UpdateAccountDetailsResponse
}

func (o *IdentitiesUpdateAccountDetailsOK) Error() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_id}/update_details][%d] identitiesUpdateAccountDetailsOK  %+v", 200, o.Payload)
}

func (o *IdentitiesUpdateAccountDetailsOK) GetPayload() models.V1UpdateAccountDetailsResponse {
	return o.Payload
}

func (o *IdentitiesUpdateAccountDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesUpdateAccountDetailsDefault creates a IdentitiesUpdateAccountDetailsDefault with default headers values
func NewIdentitiesUpdateAccountDetailsDefault(code int) *IdentitiesUpdateAccountDetailsDefault {
	return &IdentitiesUpdateAccountDetailsDefault{
		_statusCode: code,
	}
}

/*IdentitiesUpdateAccountDetailsDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesUpdateAccountDetailsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities update account details default response
func (o *IdentitiesUpdateAccountDetailsDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesUpdateAccountDetailsDefault) Error() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_id}/update_details][%d] Identities_UpdateAccountDetails default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesUpdateAccountDetailsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesUpdateAccountDetailsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
