// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// IdentitiesRemoveOrganisationMemberReader is a Reader for the IdentitiesRemoveOrganisationMember structure.
type IdentitiesRemoveOrganisationMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesRemoveOrganisationMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesRemoveOrganisationMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesRemoveOrganisationMemberDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesRemoveOrganisationMemberOK creates a IdentitiesRemoveOrganisationMemberOK with default headers values
func NewIdentitiesRemoveOrganisationMemberOK() *IdentitiesRemoveOrganisationMemberOK {
	return &IdentitiesRemoveOrganisationMemberOK{}
}

/*IdentitiesRemoveOrganisationMemberOK handles this case with default header values.

A successful response.
*/
type IdentitiesRemoveOrganisationMemberOK struct {
	Payload interface{}
}

func (o *IdentitiesRemoveOrganisationMemberOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/organisations/{organisation_id}/members/{account_id}][%d] identitiesRemoveOrganisationMemberOK  %+v", 200, o.Payload)
}

func (o *IdentitiesRemoveOrganisationMemberOK) GetPayload() interface{} {
	return o.Payload
}

func (o *IdentitiesRemoveOrganisationMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesRemoveOrganisationMemberDefault creates a IdentitiesRemoveOrganisationMemberDefault with default headers values
func NewIdentitiesRemoveOrganisationMemberDefault(code int) *IdentitiesRemoveOrganisationMemberDefault {
	return &IdentitiesRemoveOrganisationMemberDefault{
		_statusCode: code,
	}
}

/*IdentitiesRemoveOrganisationMemberDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesRemoveOrganisationMemberDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities remove organisation member default response
func (o *IdentitiesRemoveOrganisationMemberDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesRemoveOrganisationMemberDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/organisations/{organisation_id}/members/{account_id}][%d] Identities_RemoveOrganisationMember default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesRemoveOrganisationMemberDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesRemoveOrganisationMemberDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
