// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// IdentitiesTokenCheckReader is a Reader for the IdentitiesTokenCheck structure.
type IdentitiesTokenCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesTokenCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesTokenCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesTokenCheckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesTokenCheckOK creates a IdentitiesTokenCheckOK with default headers values
func NewIdentitiesTokenCheckOK() *IdentitiesTokenCheckOK {
	return &IdentitiesTokenCheckOK{}
}

/*IdentitiesTokenCheckOK handles this case with default header values.

A successful response.
*/
type IdentitiesTokenCheckOK struct {
	Payload *models.V1TokenCheckResponse
}

func (o *IdentitiesTokenCheckOK) Error() string {
	return fmt.Sprintf("[POST /v1/token/check][%d] identitiesTokenCheckOK  %+v", 200, o.Payload)
}

func (o *IdentitiesTokenCheckOK) GetPayload() *models.V1TokenCheckResponse {
	return o.Payload
}

func (o *IdentitiesTokenCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TokenCheckResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesTokenCheckDefault creates a IdentitiesTokenCheckDefault with default headers values
func NewIdentitiesTokenCheckDefault(code int) *IdentitiesTokenCheckDefault {
	return &IdentitiesTokenCheckDefault{
		_statusCode: code,
	}
}

/*IdentitiesTokenCheckDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesTokenCheckDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities token check default response
func (o *IdentitiesTokenCheckDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesTokenCheckDefault) Error() string {
	return fmt.Sprintf("[POST /v1/token/check][%d] Identities_TokenCheck default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesTokenCheckDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesTokenCheckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
