// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIdentitiesRemoveOrganisationMemberParams creates a new IdentitiesRemoveOrganisationMemberParams object
// with the default values initialized.
func NewIdentitiesRemoveOrganisationMemberParams() *IdentitiesRemoveOrganisationMemberParams {
	var ()
	return &IdentitiesRemoveOrganisationMemberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIdentitiesRemoveOrganisationMemberParamsWithTimeout creates a new IdentitiesRemoveOrganisationMemberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIdentitiesRemoveOrganisationMemberParamsWithTimeout(timeout time.Duration) *IdentitiesRemoveOrganisationMemberParams {
	var ()
	return &IdentitiesRemoveOrganisationMemberParams{

		timeout: timeout,
	}
}

// NewIdentitiesRemoveOrganisationMemberParamsWithContext creates a new IdentitiesRemoveOrganisationMemberParams object
// with the default values initialized, and the ability to set a context for a request
func NewIdentitiesRemoveOrganisationMemberParamsWithContext(ctx context.Context) *IdentitiesRemoveOrganisationMemberParams {
	var ()
	return &IdentitiesRemoveOrganisationMemberParams{

		Context: ctx,
	}
}

// NewIdentitiesRemoveOrganisationMemberParamsWithHTTPClient creates a new IdentitiesRemoveOrganisationMemberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIdentitiesRemoveOrganisationMemberParamsWithHTTPClient(client *http.Client) *IdentitiesRemoveOrganisationMemberParams {
	var ()
	return &IdentitiesRemoveOrganisationMemberParams{
		HTTPClient: client,
	}
}

/*IdentitiesRemoveOrganisationMemberParams contains all the parameters to send to the API endpoint
for the identities remove organisation member operation typically these are written to a http.Request
*/
type IdentitiesRemoveOrganisationMemberParams struct {

	/*AccountID*/
	AccountID string
	/*OrganisationID*/
	OrganisationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) WithTimeout(timeout time.Duration) *IdentitiesRemoveOrganisationMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) WithContext(ctx context.Context) *IdentitiesRemoveOrganisationMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) WithHTTPClient(client *http.Client) *IdentitiesRemoveOrganisationMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) WithAccountID(accountID string) *IdentitiesRemoveOrganisationMemberParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithOrganisationID adds the organisationID to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) WithOrganisationID(organisationID string) *IdentitiesRemoveOrganisationMemberParams {
	o.SetOrganisationID(organisationID)
	return o
}

// SetOrganisationID adds the organisationId to the identities remove organisation member params
func (o *IdentitiesRemoveOrganisationMemberParams) SetOrganisationID(organisationID string) {
	o.OrganisationID = organisationID
}

// WriteToRequest writes these params to a swagger request
func (o *IdentitiesRemoveOrganisationMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", o.AccountID); err != nil {
		return err
	}

	// path param organisation_id
	if err := r.SetPathParam("organisation_id", o.OrganisationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
