// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewIdentitiesUpdateAccountPasswordParams creates a new IdentitiesUpdateAccountPasswordParams object
// with the default values initialized.
func NewIdentitiesUpdateAccountPasswordParams() *IdentitiesUpdateAccountPasswordParams {
	var ()
	return &IdentitiesUpdateAccountPasswordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIdentitiesUpdateAccountPasswordParamsWithTimeout creates a new IdentitiesUpdateAccountPasswordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIdentitiesUpdateAccountPasswordParamsWithTimeout(timeout time.Duration) *IdentitiesUpdateAccountPasswordParams {
	var ()
	return &IdentitiesUpdateAccountPasswordParams{

		timeout: timeout,
	}
}

// NewIdentitiesUpdateAccountPasswordParamsWithContext creates a new IdentitiesUpdateAccountPasswordParams object
// with the default values initialized, and the ability to set a context for a request
func NewIdentitiesUpdateAccountPasswordParamsWithContext(ctx context.Context) *IdentitiesUpdateAccountPasswordParams {
	var ()
	return &IdentitiesUpdateAccountPasswordParams{

		Context: ctx,
	}
}

// NewIdentitiesUpdateAccountPasswordParamsWithHTTPClient creates a new IdentitiesUpdateAccountPasswordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIdentitiesUpdateAccountPasswordParamsWithHTTPClient(client *http.Client) *IdentitiesUpdateAccountPasswordParams {
	var ()
	return &IdentitiesUpdateAccountPasswordParams{
		HTTPClient: client,
	}
}

/*IdentitiesUpdateAccountPasswordParams contains all the parameters to send to the API endpoint
for the identities update account password operation typically these are written to a http.Request
*/
type IdentitiesUpdateAccountPasswordParams struct {

	/*AccountID*/
	AccountID string
	/*Body*/
	Body *models.V1UpdateAccountPasswordRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) WithTimeout(timeout time.Duration) *IdentitiesUpdateAccountPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) WithContext(ctx context.Context) *IdentitiesUpdateAccountPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) WithHTTPClient(client *http.Client) *IdentitiesUpdateAccountPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) WithAccountID(accountID string) *IdentitiesUpdateAccountPasswordParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithBody adds the body to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) WithBody(body *models.V1UpdateAccountPasswordRequest) *IdentitiesUpdateAccountPasswordParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the identities update account password params
func (o *IdentitiesUpdateAccountPasswordParams) SetBody(body *models.V1UpdateAccountPasswordRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IdentitiesUpdateAccountPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", o.AccountID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
