// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// QueryOrganisationsReader is a Reader for the QueryOrganisations structure.
type QueryOrganisationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryOrganisationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryOrganisationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewQueryOrganisationsOK creates a QueryOrganisationsOK with default headers values
func NewQueryOrganisationsOK() *QueryOrganisationsOK {
	return &QueryOrganisationsOK{}
}

/*QueryOrganisationsOK handles this case with default header values.

A successful response.
*/
type QueryOrganisationsOK struct {
	Payload *models.V1QueryOrganisationsResponse
}

func (o *QueryOrganisationsOK) Error() string {
	return fmt.Sprintf("[GET /v1/organisations][%d] queryOrganisationsOK  %+v", 200, o.Payload)
}

func (o *QueryOrganisationsOK) GetPayload() *models.V1QueryOrganisationsResponse {
	return o.Payload
}

func (o *QueryOrganisationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1QueryOrganisationsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
