// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// QueryAccountsReader is a Reader for the QueryAccounts structure.
type QueryAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewQueryAccountsOK creates a QueryAccountsOK with default headers values
func NewQueryAccountsOK() *QueryAccountsOK {
	return &QueryAccountsOK{}
}

/*QueryAccountsOK handles this case with default header values.

A successful response.
*/
type QueryAccountsOK struct {
	Payload *models.V1QueryAccountsResponse
}

func (o *QueryAccountsOK) Error() string {
	return fmt.Sprintf("[GET /v1/accounts][%d] queryAccountsOK  %+v", 200, o.Payload)
}

func (o *QueryAccountsOK) GetPayload() *models.V1QueryAccountsResponse {
	return o.Payload
}

func (o *QueryAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1QueryAccountsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
