// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewSendResetPasswordParams creates a new SendResetPasswordParams object
// with the default values initialized.
func NewSendResetPasswordParams() *SendResetPasswordParams {
	var ()
	return &SendResetPasswordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendResetPasswordParamsWithTimeout creates a new SendResetPasswordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendResetPasswordParamsWithTimeout(timeout time.Duration) *SendResetPasswordParams {
	var ()
	return &SendResetPasswordParams{

		timeout: timeout,
	}
}

// NewSendResetPasswordParamsWithContext creates a new SendResetPasswordParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendResetPasswordParamsWithContext(ctx context.Context) *SendResetPasswordParams {
	var ()
	return &SendResetPasswordParams{

		Context: ctx,
	}
}

// NewSendResetPasswordParamsWithHTTPClient creates a new SendResetPasswordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSendResetPasswordParamsWithHTTPClient(client *http.Client) *SendResetPasswordParams {
	var ()
	return &SendResetPasswordParams{
		HTTPClient: client,
	}
}

/*SendResetPasswordParams contains all the parameters to send to the API endpoint
for the send reset password operation typically these are written to a http.Request
*/
type SendResetPasswordParams struct {

	/*Body*/
	Body *models.V1SendResetPasswordRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send reset password params
func (o *SendResetPasswordParams) WithTimeout(timeout time.Duration) *SendResetPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send reset password params
func (o *SendResetPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send reset password params
func (o *SendResetPasswordParams) WithContext(ctx context.Context) *SendResetPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send reset password params
func (o *SendResetPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send reset password params
func (o *SendResetPasswordParams) WithHTTPClient(client *http.Client) *SendResetPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send reset password params
func (o *SendResetPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send reset password params
func (o *SendResetPasswordParams) WithBody(body *models.V1SendResetPasswordRequest) *SendResetPasswordParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send reset password params
func (o *SendResetPasswordParams) SetBody(body *models.V1SendResetPasswordRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SendResetPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
