// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// SendResetPasswordReader is a Reader for the SendResetPassword structure.
type SendResetPasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendResetPasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSendResetPasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendResetPasswordOK creates a SendResetPasswordOK with default headers values
func NewSendResetPasswordOK() *SendResetPasswordOK {
	return &SendResetPasswordOK{}
}

/*SendResetPasswordOK handles this case with default header values.

A successful response.
*/
type SendResetPasswordOK struct {
	Payload models.V1SendResetPasswordResponse
}

func (o *SendResetPasswordOK) Error() string {
	return fmt.Sprintf("[POST /v1/users/send-reset][%d] sendResetPasswordOK  %+v", 200, o.Payload)
}

func (o *SendResetPasswordOK) GetPayload() models.V1SendResetPasswordResponse {
	return o.Payload
}

func (o *SendResetPasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
