// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewTokenCheckParams creates a new TokenCheckParams object
// with the default values initialized.
func NewTokenCheckParams() *TokenCheckParams {
	var ()
	return &TokenCheckParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTokenCheckParamsWithTimeout creates a new TokenCheckParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTokenCheckParamsWithTimeout(timeout time.Duration) *TokenCheckParams {
	var ()
	return &TokenCheckParams{

		timeout: timeout,
	}
}

// NewTokenCheckParamsWithContext creates a new TokenCheckParams object
// with the default values initialized, and the ability to set a context for a request
func NewTokenCheckParamsWithContext(ctx context.Context) *TokenCheckParams {
	var ()
	return &TokenCheckParams{

		Context: ctx,
	}
}

// NewTokenCheckParamsWithHTTPClient creates a new TokenCheckParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTokenCheckParamsWithHTTPClient(client *http.Client) *TokenCheckParams {
	var ()
	return &TokenCheckParams{
		HTTPClient: client,
	}
}

/*TokenCheckParams contains all the parameters to send to the API endpoint
for the token check operation typically these are written to a http.Request
*/
type TokenCheckParams struct {

	/*Body*/
	Body *models.V1TokenCheckRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the token check params
func (o *TokenCheckParams) WithTimeout(timeout time.Duration) *TokenCheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the token check params
func (o *TokenCheckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the token check params
func (o *TokenCheckParams) WithContext(ctx context.Context) *TokenCheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the token check params
func (o *TokenCheckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the token check params
func (o *TokenCheckParams) WithHTTPClient(client *http.Client) *TokenCheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the token check params
func (o *TokenCheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the token check params
func (o *TokenCheckParams) WithBody(body *models.V1TokenCheckRequest) *TokenCheckParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the token check params
func (o *TokenCheckParams) SetBody(body *models.V1TokenCheckRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TokenCheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
