// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewTokenRenewParams creates a new TokenRenewParams object
// with the default values initialized.
func NewTokenRenewParams() *TokenRenewParams {
	var ()
	return &TokenRenewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTokenRenewParamsWithTimeout creates a new TokenRenewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTokenRenewParamsWithTimeout(timeout time.Duration) *TokenRenewParams {
	var ()
	return &TokenRenewParams{

		timeout: timeout,
	}
}

// NewTokenRenewParamsWithContext creates a new TokenRenewParams object
// with the default values initialized, and the ability to set a context for a request
func NewTokenRenewParamsWithContext(ctx context.Context) *TokenRenewParams {
	var ()
	return &TokenRenewParams{

		Context: ctx,
	}
}

// NewTokenRenewParamsWithHTTPClient creates a new TokenRenewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTokenRenewParamsWithHTTPClient(client *http.Client) *TokenRenewParams {
	var ()
	return &TokenRenewParams{
		HTTPClient: client,
	}
}

/*TokenRenewParams contains all the parameters to send to the API endpoint
for the token renew operation typically these are written to a http.Request
*/
type TokenRenewParams struct {

	/*Body*/
	Body *models.V1TokenRenewRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the token renew params
func (o *TokenRenewParams) WithTimeout(timeout time.Duration) *TokenRenewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the token renew params
func (o *TokenRenewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the token renew params
func (o *TokenRenewParams) WithContext(ctx context.Context) *TokenRenewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the token renew params
func (o *TokenRenewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the token renew params
func (o *TokenRenewParams) WithHTTPClient(client *http.Client) *TokenRenewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the token renew params
func (o *TokenRenewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the token renew params
func (o *TokenRenewParams) WithBody(body *models.V1TokenRenewRequest) *TokenRenewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the token renew params
func (o *TokenRenewParams) SetBody(body *models.V1TokenRenewRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TokenRenewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
