// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewTokenRevokeParams creates a new TokenRevokeParams object
// with the default values initialized.
func NewTokenRevokeParams() *TokenRevokeParams {
	var ()
	return &TokenRevokeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTokenRevokeParamsWithTimeout creates a new TokenRevokeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTokenRevokeParamsWithTimeout(timeout time.Duration) *TokenRevokeParams {
	var ()
	return &TokenRevokeParams{

		timeout: timeout,
	}
}

// NewTokenRevokeParamsWithContext creates a new TokenRevokeParams object
// with the default values initialized, and the ability to set a context for a request
func NewTokenRevokeParamsWithContext(ctx context.Context) *TokenRevokeParams {
	var ()
	return &TokenRevokeParams{

		Context: ctx,
	}
}

// NewTokenRevokeParamsWithHTTPClient creates a new TokenRevokeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTokenRevokeParamsWithHTTPClient(client *http.Client) *TokenRevokeParams {
	var ()
	return &TokenRevokeParams{
		HTTPClient: client,
	}
}

/*TokenRevokeParams contains all the parameters to send to the API endpoint
for the token revoke operation typically these are written to a http.Request
*/
type TokenRevokeParams struct {

	/*Body*/
	Body *models.V1TokenRevokeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the token revoke params
func (o *TokenRevokeParams) WithTimeout(timeout time.Duration) *TokenRevokeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the token revoke params
func (o *TokenRevokeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the token revoke params
func (o *TokenRevokeParams) WithContext(ctx context.Context) *TokenRevokeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the token revoke params
func (o *TokenRevokeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the token revoke params
func (o *TokenRevokeParams) WithHTTPClient(client *http.Client) *TokenRevokeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the token revoke params
func (o *TokenRevokeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the token revoke params
func (o *TokenRevokeParams) WithBody(body *models.V1TokenRevokeRequest) *TokenRevokeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the token revoke params
func (o *TokenRevokeParams) SetBody(body *models.V1TokenRevokeRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TokenRevokeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
