// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// TokenRenewReader is a Reader for the TokenRenew structure.
type TokenRenewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TokenRenewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTokenRenewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTokenRenewOK creates a TokenRenewOK with default headers values
func NewTokenRenewOK() *TokenRenewOK {
	return &TokenRenewOK{}
}

/*TokenRenewOK handles this case with default header values.

A successful response.
*/
type TokenRenewOK struct {
	Payload *models.V1TokenRenewResponse
}

func (o *TokenRenewOK) Error() string {
	return fmt.Sprintf("[POST /v1/token/renew][%d] tokenRenewOK  %+v", 200, o.Payload)
}

func (o *TokenRenewOK) GetPayload() *models.V1TokenRenewResponse {
	return o.Payload
}

func (o *TokenRenewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TokenRenewResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
