// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identity/models"
)

// NewUpdateAccountDetailsParams creates a new UpdateAccountDetailsParams object
// with the default values initialized.
func NewUpdateAccountDetailsParams() *UpdateAccountDetailsParams {
	var ()
	return &UpdateAccountDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAccountDetailsParamsWithTimeout creates a new UpdateAccountDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAccountDetailsParamsWithTimeout(timeout time.Duration) *UpdateAccountDetailsParams {
	var ()
	return &UpdateAccountDetailsParams{

		timeout: timeout,
	}
}

// NewUpdateAccountDetailsParamsWithContext creates a new UpdateAccountDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAccountDetailsParamsWithContext(ctx context.Context) *UpdateAccountDetailsParams {
	var ()
	return &UpdateAccountDetailsParams{

		Context: ctx,
	}
}

// NewUpdateAccountDetailsParamsWithHTTPClient creates a new UpdateAccountDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAccountDetailsParamsWithHTTPClient(client *http.Client) *UpdateAccountDetailsParams {
	var ()
	return &UpdateAccountDetailsParams{
		HTTPClient: client,
	}
}

/*UpdateAccountDetailsParams contains all the parameters to send to the API endpoint
for the update account details operation typically these are written to a http.Request
*/
type UpdateAccountDetailsParams struct {

	/*AccountID*/
	AccountID string
	/*Body*/
	Body *models.V1UpdateAccountDetailsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update account details params
func (o *UpdateAccountDetailsParams) WithTimeout(timeout time.Duration) *UpdateAccountDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update account details params
func (o *UpdateAccountDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update account details params
func (o *UpdateAccountDetailsParams) WithContext(ctx context.Context) *UpdateAccountDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update account details params
func (o *UpdateAccountDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update account details params
func (o *UpdateAccountDetailsParams) WithHTTPClient(client *http.Client) *UpdateAccountDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update account details params
func (o *UpdateAccountDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the update account details params
func (o *UpdateAccountDetailsParams) WithAccountID(accountID string) *UpdateAccountDetailsParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the update account details params
func (o *UpdateAccountDetailsParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithBody adds the body to the update account details params
func (o *UpdateAccountDetailsParams) WithBody(body *models.V1UpdateAccountDetailsRequest) *UpdateAccountDetailsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update account details params
func (o *UpdateAccountDetailsParams) SetBody(body *models.V1UpdateAccountDetailsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccountDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", o.AccountID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
