// Code generated by go-swagger; DO NOT EDIT.

package introducers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIntroducerParams creates a new GetIntroducerParams object
// with the default values initialized.
func NewGetIntroducerParams() *GetIntroducerParams {
	var ()
	return &GetIntroducerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIntroducerParamsWithTimeout creates a new GetIntroducerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIntroducerParamsWithTimeout(timeout time.Duration) *GetIntroducerParams {
	var ()
	return &GetIntroducerParams{

		timeout: timeout,
	}
}

// NewGetIntroducerParamsWithContext creates a new GetIntroducerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIntroducerParamsWithContext(ctx context.Context) *GetIntroducerParams {
	var ()
	return &GetIntroducerParams{

		Context: ctx,
	}
}

// NewGetIntroducerParamsWithHTTPClient creates a new GetIntroducerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIntroducerParamsWithHTTPClient(client *http.Client) *GetIntroducerParams {
	var ()
	return &GetIntroducerParams{
		HTTPClient: client,
	}
}

/*GetIntroducerParams contains all the parameters to send to the API endpoint
for the get introducer operation typically these are written to a http.Request
*/
type GetIntroducerParams struct {

	/*IntroducerID*/
	IntroducerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get introducer params
func (o *GetIntroducerParams) WithTimeout(timeout time.Duration) *GetIntroducerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get introducer params
func (o *GetIntroducerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get introducer params
func (o *GetIntroducerParams) WithContext(ctx context.Context) *GetIntroducerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get introducer params
func (o *GetIntroducerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get introducer params
func (o *GetIntroducerParams) WithHTTPClient(client *http.Client) *GetIntroducerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get introducer params
func (o *GetIntroducerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntroducerID adds the introducerID to the get introducer params
func (o *GetIntroducerParams) WithIntroducerID(introducerID string) *GetIntroducerParams {
	o.SetIntroducerID(introducerID)
	return o
}

// SetIntroducerID adds the introducerId to the get introducer params
func (o *GetIntroducerParams) SetIntroducerID(introducerID string) {
	o.IntroducerID = introducerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetIntroducerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param introducer_id
	if err := r.SetPathParam("introducer_id", o.IntroducerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
