// Code generated by go-swagger; DO NOT EDIT.

package introducers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RemoveIntroducerOwnerReader is a Reader for the RemoveIntroducerOwner structure.
type RemoveIntroducerOwnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveIntroducerOwnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveIntroducerOwnerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveIntroducerOwnerOK creates a RemoveIntroducerOwnerOK with default headers values
func NewRemoveIntroducerOwnerOK() *RemoveIntroducerOwnerOK {
	return &RemoveIntroducerOwnerOK{}
}

/*RemoveIntroducerOwnerOK handles this case with default header values.

A successful response.
*/
type RemoveIntroducerOwnerOK struct {
	Payload interface{}
}

func (o *RemoveIntroducerOwnerOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/introducers/{introducer_id}/owners/{account_id}][%d] removeIntroducerOwnerOK  %+v", 200, o.Payload)
}

func (o *RemoveIntroducerOwnerOK) GetPayload() interface{} {
	return o.Payload
}

func (o *RemoveIntroducerOwnerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
