// Code generated by go-swagger; DO NOT EDIT.

package introducers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/introducers/models"
)

// UpdateIntroducerAddressReader is a Reader for the UpdateIntroducerAddress structure.
type UpdateIntroducerAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateIntroducerAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateIntroducerAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateIntroducerAddressOK creates a UpdateIntroducerAddressOK with default headers values
func NewUpdateIntroducerAddressOK() *UpdateIntroducerAddressOK {
	return &UpdateIntroducerAddressOK{}
}

/*UpdateIntroducerAddressOK handles this case with default header values.

A successful response.
*/
type UpdateIntroducerAddressOK struct {
	Payload models.V1UpdateIntroducerAddressResponse
}

func (o *UpdateIntroducerAddressOK) Error() string {
	return fmt.Sprintf("[POST /v1/introducers/{introducer_id}/update_address][%d] updateIntroducerAddressOK  %+v", 200, o.Payload)
}

func (o *UpdateIntroducerAddressOK) GetPayload() models.V1UpdateIntroducerAddressResponse {
	return o.Payload
}

func (o *UpdateIntroducerAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
