// Code generated by go-swagger; DO NOT EDIT.

package introducers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/introducers/models"
)

// NewUpdateIntroducerAddressParams creates a new UpdateIntroducerAddressParams object
// with the default values initialized.
func NewUpdateIntroducerAddressParams() *UpdateIntroducerAddressParams {
	var ()
	return &UpdateIntroducerAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateIntroducerAddressParamsWithTimeout creates a new UpdateIntroducerAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateIntroducerAddressParamsWithTimeout(timeout time.Duration) *UpdateIntroducerAddressParams {
	var ()
	return &UpdateIntroducerAddressParams{

		timeout: timeout,
	}
}

// NewUpdateIntroducerAddressParamsWithContext creates a new UpdateIntroducerAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateIntroducerAddressParamsWithContext(ctx context.Context) *UpdateIntroducerAddressParams {
	var ()
	return &UpdateIntroducerAddressParams{

		Context: ctx,
	}
}

// NewUpdateIntroducerAddressParamsWithHTTPClient creates a new UpdateIntroducerAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateIntroducerAddressParamsWithHTTPClient(client *http.Client) *UpdateIntroducerAddressParams {
	var ()
	return &UpdateIntroducerAddressParams{
		HTTPClient: client,
	}
}

/*UpdateIntroducerAddressParams contains all the parameters to send to the API endpoint
for the update introducer address operation typically these are written to a http.Request
*/
type UpdateIntroducerAddressParams struct {

	/*Body*/
	Body *models.V1UpdateIntroducerAddressRequest
	/*IntroducerID*/
	IntroducerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update introducer address params
func (o *UpdateIntroducerAddressParams) WithTimeout(timeout time.Duration) *UpdateIntroducerAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update introducer address params
func (o *UpdateIntroducerAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update introducer address params
func (o *UpdateIntroducerAddressParams) WithContext(ctx context.Context) *UpdateIntroducerAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update introducer address params
func (o *UpdateIntroducerAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update introducer address params
func (o *UpdateIntroducerAddressParams) WithHTTPClient(client *http.Client) *UpdateIntroducerAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update introducer address params
func (o *UpdateIntroducerAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update introducer address params
func (o *UpdateIntroducerAddressParams) WithBody(body *models.V1UpdateIntroducerAddressRequest) *UpdateIntroducerAddressParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update introducer address params
func (o *UpdateIntroducerAddressParams) SetBody(body *models.V1UpdateIntroducerAddressRequest) {
	o.Body = body
}

// WithIntroducerID adds the introducerID to the update introducer address params
func (o *UpdateIntroducerAddressParams) WithIntroducerID(introducerID string) *UpdateIntroducerAddressParams {
	o.SetIntroducerID(introducerID)
	return o
}

// SetIntroducerID adds the introducerId to the update introducer address params
func (o *UpdateIntroducerAddressParams) SetIntroducerID(introducerID string) {
	o.IntroducerID = introducerID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateIntroducerAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param introducer_id
	if err := r.SetPathParam("introducer_id", o.IntroducerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
