// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// InternalwktOccupancyType - OT_LOCAL_AUTH_RENTING: Local authority renting/housing association
// swagger:model internalwktOccupancyType
type InternalwktOccupancyType string

const (

	// InternalwktOccupancyTypeOTUNKOWN captures enum value "OT_UNKOWN"
	InternalwktOccupancyTypeOTUNKOWN InternalwktOccupancyType = "OT_UNKOWN"

	// InternalwktOccupancyTypeOTOWNERWITHMORTGAGE captures enum value "OT_OWNER_WITH_MORTGAGE"
	InternalwktOccupancyTypeOTOWNERWITHMORTGAGE InternalwktOccupancyType = "OT_OWNER_WITH_MORTGAGE"

	// InternalwktOccupancyTypeOTOWNERWITHOUTMORTGAGE captures enum value "OT_OWNER_WITHOUT_MORTGAGE"
	InternalwktOccupancyTypeOTOWNERWITHOUTMORTGAGE InternalwktOccupancyType = "OT_OWNER_WITHOUT_MORTGAGE"

	// InternalwktOccupancyTypeOTPRIVATERENT captures enum value "OT_PRIVATE_RENT"
	InternalwktOccupancyTypeOTPRIVATERENT InternalwktOccupancyType = "OT_PRIVATE_RENT"

	// InternalwktOccupancyTypeOTLIVINGWITHPARENTS captures enum value "OT_LIVING_WITH_PARENTS"
	InternalwktOccupancyTypeOTLIVINGWITHPARENTS InternalwktOccupancyType = "OT_LIVING_WITH_PARENTS"

	// InternalwktOccupancyTypeOTLIVINGWITHFRIENDS captures enum value "OT_LIVING_WITH_FRIENDS"
	InternalwktOccupancyTypeOTLIVINGWITHFRIENDS InternalwktOccupancyType = "OT_LIVING_WITH_FRIENDS"

	// InternalwktOccupancyTypeOTTIEDACCOMMODATION captures enum value "OT_TIED_ACCOMMODATION"
	InternalwktOccupancyTypeOTTIEDACCOMMODATION InternalwktOccupancyType = "OT_TIED_ACCOMMODATION"

	// InternalwktOccupancyTypeOTLOCALAUTHRENTING captures enum value "OT_LOCAL_AUTH_RENTING"
	InternalwktOccupancyTypeOTLOCALAUTHRENTING InternalwktOccupancyType = "OT_LOCAL_AUTH_RENTING"
)

// for schema
var internalwktOccupancyTypeEnum []interface{}

func init() {
	var res []InternalwktOccupancyType
	if err := json.Unmarshal([]byte(`["OT_UNKOWN","OT_OWNER_WITH_MORTGAGE","OT_OWNER_WITHOUT_MORTGAGE","OT_PRIVATE_RENT","OT_LIVING_WITH_PARENTS","OT_LIVING_WITH_FRIENDS","OT_TIED_ACCOMMODATION","OT_LOCAL_AUTH_RENTING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		internalwktOccupancyTypeEnum = append(internalwktOccupancyTypeEnum, v)
	}
}

func (m InternalwktOccupancyType) validateInternalwktOccupancyTypeEnum(path, location string, value InternalwktOccupancyType) error {
	if err := validate.Enum(path, location, value, internalwktOccupancyTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this internalwkt occupancy type
func (m InternalwktOccupancyType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateInternalwktOccupancyTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
