// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProfileCustodialSentence profile custodial sentence
// swagger:model ProfileCustodialSentence
type ProfileCustodialSentence struct {

	// The nature of the conviction.
	Nature string `json:"nature,omitempty"`

	// The total amount of full months served for example 4 years
	// 6 months would be 54.
	// Please include any suspended sentences.
	ServedMonths int32 `json:"served_months,omitempty"`

	// The start date the defendant started their custodial sentence.
	Start *InternalwktDate `json:"start,omitempty"`
}

// Validate validates this profile custodial sentence
func (m *ProfileCustodialSentence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStart(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProfileCustodialSentence) validateStart(formats strfmt.Registry) error {

	if swag.IsZero(m.Start) { // not required
		return nil
	}

	if m.Start != nil {
		if err := m.Start.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("start")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProfileCustodialSentence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProfileCustodialSentence) UnmarshalBinary(b []byte) error {
	var res ProfileCustodialSentence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
