// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AddOwnershipResponse v1 add ownership response
// swagger:model v1AddOwnershipResponse
type V1AddOwnershipResponse struct {

	// ownership id
	OwnershipID string `json:"ownership_id,omitempty"`
}

// Validate validates this v1 add ownership response
func (m *V1AddOwnershipResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AddOwnershipResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AddOwnershipResponse) UnmarshalBinary(b []byte) error {
	var res V1AddOwnershipResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
