// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1AssetPropertyPropertyType v1 asset property property type
// swagger:model v1AssetPropertyPropertyType
type V1AssetPropertyPropertyType string

const (

	// V1AssetPropertyPropertyTypePROPERTYTYPERESIDENTIAL captures enum value "PROPERTY_TYPE_RESIDENTIAL"
	V1AssetPropertyPropertyTypePROPERTYTYPERESIDENTIAL V1AssetPropertyPropertyType = "PROPERTY_TYPE_RESIDENTIAL"

	// V1AssetPropertyPropertyTypePROPERTYTYPESEMICOMMERCIAL captures enum value "PROPERTY_TYPE_SEMI_COMMERCIAL"
	V1AssetPropertyPropertyTypePROPERTYTYPESEMICOMMERCIAL V1AssetPropertyPropertyType = "PROPERTY_TYPE_SEMI_COMMERCIAL"

	// V1AssetPropertyPropertyTypePROPERTYTYPECOMMERCIAL captures enum value "PROPERTY_TYPE_COMMERCIAL"
	V1AssetPropertyPropertyTypePROPERTYTYPECOMMERCIAL V1AssetPropertyPropertyType = "PROPERTY_TYPE_COMMERCIAL"

	// V1AssetPropertyPropertyTypePROPERTYTYPERETAIL captures enum value "PROPERTY_TYPE_RETAIL"
	V1AssetPropertyPropertyTypePROPERTYTYPERETAIL V1AssetPropertyPropertyType = "PROPERTY_TYPE_RETAIL"

	// V1AssetPropertyPropertyTypePROPERTYTYPEAGRICULTURAL captures enum value "PROPERTY_TYPE_AGRICULTURAL"
	V1AssetPropertyPropertyTypePROPERTYTYPEAGRICULTURAL V1AssetPropertyPropertyType = "PROPERTY_TYPE_AGRICULTURAL"

	// V1AssetPropertyPropertyTypePROPERTYTYPELEISURE captures enum value "PROPERTY_TYPE_LEISURE"
	V1AssetPropertyPropertyTypePROPERTYTYPELEISURE V1AssetPropertyPropertyType = "PROPERTY_TYPE_LEISURE"

	// V1AssetPropertyPropertyTypePROPERTYTYPELAND captures enum value "PROPERTY_TYPE_LAND"
	V1AssetPropertyPropertyTypePROPERTYTYPELAND V1AssetPropertyPropertyType = "PROPERTY_TYPE_LAND"

	// V1AssetPropertyPropertyTypePROPERTYTYPECARE captures enum value "PROPERTY_TYPE_CARE"
	V1AssetPropertyPropertyTypePROPERTYTYPECARE V1AssetPropertyPropertyType = "PROPERTY_TYPE_CARE"

	// V1AssetPropertyPropertyTypePROPERTYTYPEPROFESSIONALPRACTICE captures enum value "PROPERTY_TYPE_PROFESSIONAL_PRACTICE"
	V1AssetPropertyPropertyTypePROPERTYTYPEPROFESSIONALPRACTICE V1AssetPropertyPropertyType = "PROPERTY_TYPE_PROFESSIONAL_PRACTICE"

	// V1AssetPropertyPropertyTypePROPERTYTYPEDEVELOPMENT captures enum value "PROPERTY_TYPE_DEVELOPMENT"
	V1AssetPropertyPropertyTypePROPERTYTYPEDEVELOPMENT V1AssetPropertyPropertyType = "PROPERTY_TYPE_DEVELOPMENT"
)

// for schema
var v1AssetPropertyPropertyTypeEnum []interface{}

func init() {
	var res []V1AssetPropertyPropertyType
	if err := json.Unmarshal([]byte(`["PROPERTY_TYPE_RESIDENTIAL","PROPERTY_TYPE_SEMI_COMMERCIAL","PROPERTY_TYPE_COMMERCIAL","PROPERTY_TYPE_RETAIL","PROPERTY_TYPE_AGRICULTURAL","PROPERTY_TYPE_LEISURE","PROPERTY_TYPE_LAND","PROPERTY_TYPE_CARE","PROPERTY_TYPE_PROFESSIONAL_PRACTICE","PROPERTY_TYPE_DEVELOPMENT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1AssetPropertyPropertyTypeEnum = append(v1AssetPropertyPropertyTypeEnum, v)
	}
}

func (m V1AssetPropertyPropertyType) validateV1AssetPropertyPropertyTypeEnum(path, location string, value V1AssetPropertyPropertyType) error {
	if err := validate.Enum(path, location, value, v1AssetPropertyPropertyTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 asset property property type
func (m V1AssetPropertyPropertyType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1AssetPropertyPropertyTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
