// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateDownloadDocumentLinkRequest v1 create download document link request
// swagger:model v1CreateDownloadDocumentLinkRequest
type V1CreateDownloadDocumentLinkRequest struct {

	// collection id
	CollectionID string `json:"collection_id,omitempty"`

	// document id
	DocumentID string `json:"document_id,omitempty"`
}

// Validate validates this v1 create download document link request
func (m *V1CreateDownloadDocumentLinkRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateDownloadDocumentLinkRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateDownloadDocumentLinkRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateDownloadDocumentLinkRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
