// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1DeleteDocumentResponse v1 delete document response
// swagger:model v1DeleteDocumentResponse
type V1DeleteDocumentResponse interface{}
