// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1RemoveEmploymentResponse v1 remove employment response
// swagger:model v1RemoveEmploymentResponse
type V1RemoveEmploymentResponse interface{}
