// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1SetAddressHistoryResponse v1 set address history response
// swagger:model v1SetAddressHistoryResponse
type V1SetAddressHistoryResponse interface{}
