// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1SetEmploymentResponse v1 set employment response
// swagger:model v1SetEmploymentResponse
type V1SetEmploymentResponse interface{}
