// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1UpdateOwnershipResponse v1 update ownership response
// swagger:model v1UpdateOwnershipResponse
type V1UpdateOwnershipResponse interface{}
