// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// NewCustomerGatewayAddCompanyParams creates a new CustomerGatewayAddCompanyParams object
// with the default values initialized.
func NewCustomerGatewayAddCompanyParams() *CustomerGatewayAddCompanyParams {
	var ()
	return &CustomerGatewayAddCompanyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayAddCompanyParamsWithTimeout creates a new CustomerGatewayAddCompanyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayAddCompanyParamsWithTimeout(timeout time.Duration) *CustomerGatewayAddCompanyParams {
	var ()
	return &CustomerGatewayAddCompanyParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayAddCompanyParamsWithContext creates a new CustomerGatewayAddCompanyParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayAddCompanyParamsWithContext(ctx context.Context) *CustomerGatewayAddCompanyParams {
	var ()
	return &CustomerGatewayAddCompanyParams{

		Context: ctx,
	}
}

// NewCustomerGatewayAddCompanyParamsWithHTTPClient creates a new CustomerGatewayAddCompanyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayAddCompanyParamsWithHTTPClient(client *http.Client) *CustomerGatewayAddCompanyParams {
	var ()
	return &CustomerGatewayAddCompanyParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayAddCompanyParams contains all the parameters to send to the API endpoint
for the customer gateway add company operation typically these are written to a http.Request
*/
type CustomerGatewayAddCompanyParams struct {

	/*Body*/
	Body models.V1AddCompanyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) WithTimeout(timeout time.Duration) *CustomerGatewayAddCompanyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) WithContext(ctx context.Context) *CustomerGatewayAddCompanyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) WithHTTPClient(client *http.Client) *CustomerGatewayAddCompanyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) WithBody(body models.V1AddCompanyRequest) *CustomerGatewayAddCompanyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer gateway add company params
func (o *CustomerGatewayAddCompanyParams) SetBody(body models.V1AddCompanyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayAddCompanyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
