// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayGetApplicationReader is a Reader for the CustomerGatewayGetApplication structure.
type CustomerGatewayGetApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayGetApplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayGetApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayGetApplicationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayGetApplicationOK creates a CustomerGatewayGetApplicationOK with default headers values
func NewCustomerGatewayGetApplicationOK() *CustomerGatewayGetApplicationOK {
	return &CustomerGatewayGetApplicationOK{}
}

/*CustomerGatewayGetApplicationOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayGetApplicationOK struct {
	Payload *models.V1GetApplicationResponse
}

func (o *CustomerGatewayGetApplicationOK) Error() string {
	return fmt.Sprintf("[GET /v1/applications/{app_type}/{app_id}][%d] customerGatewayGetApplicationOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayGetApplicationOK) GetPayload() *models.V1GetApplicationResponse {
	return o.Payload
}

func (o *CustomerGatewayGetApplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetApplicationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayGetApplicationDefault creates a CustomerGatewayGetApplicationDefault with default headers values
func NewCustomerGatewayGetApplicationDefault(code int) *CustomerGatewayGetApplicationDefault {
	return &CustomerGatewayGetApplicationDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayGetApplicationDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayGetApplicationDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway get application default response
func (o *CustomerGatewayGetApplicationDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayGetApplicationDefault) Error() string {
	return fmt.Sprintf("[GET /v1/applications/{app_type}/{app_id}][%d] CustomerGateway_GetApplication default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayGetApplicationDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayGetApplicationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
