// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayGetSummaryReader is a Reader for the CustomerGatewayGetSummary structure.
type CustomerGatewayGetSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayGetSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayGetSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayGetSummaryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayGetSummaryOK creates a CustomerGatewayGetSummaryOK with default headers values
func NewCustomerGatewayGetSummaryOK() *CustomerGatewayGetSummaryOK {
	return &CustomerGatewayGetSummaryOK{}
}

/*CustomerGatewayGetSummaryOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayGetSummaryOK struct {
	Payload *models.V1GetSummaryResponse
}

func (o *CustomerGatewayGetSummaryOK) Error() string {
	return fmt.Sprintf("[GET /v1/summary][%d] customerGatewayGetSummaryOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayGetSummaryOK) GetPayload() *models.V1GetSummaryResponse {
	return o.Payload
}

func (o *CustomerGatewayGetSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetSummaryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayGetSummaryDefault creates a CustomerGatewayGetSummaryDefault with default headers values
func NewCustomerGatewayGetSummaryDefault(code int) *CustomerGatewayGetSummaryDefault {
	return &CustomerGatewayGetSummaryDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayGetSummaryDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayGetSummaryDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway get summary default response
func (o *CustomerGatewayGetSummaryDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayGetSummaryDefault) Error() string {
	return fmt.Sprintf("[GET /v1/summary][%d] CustomerGateway_GetSummary default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayGetSummaryDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayGetSummaryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
