// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerGatewayDeleteDocumentParams creates a new CustomerGatewayDeleteDocumentParams object
// with the default values initialized.
func NewCustomerGatewayDeleteDocumentParams() *CustomerGatewayDeleteDocumentParams {
	var ()
	return &CustomerGatewayDeleteDocumentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayDeleteDocumentParamsWithTimeout creates a new CustomerGatewayDeleteDocumentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayDeleteDocumentParamsWithTimeout(timeout time.Duration) *CustomerGatewayDeleteDocumentParams {
	var ()
	return &CustomerGatewayDeleteDocumentParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayDeleteDocumentParamsWithContext creates a new CustomerGatewayDeleteDocumentParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayDeleteDocumentParamsWithContext(ctx context.Context) *CustomerGatewayDeleteDocumentParams {
	var ()
	return &CustomerGatewayDeleteDocumentParams{

		Context: ctx,
	}
}

// NewCustomerGatewayDeleteDocumentParamsWithHTTPClient creates a new CustomerGatewayDeleteDocumentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayDeleteDocumentParamsWithHTTPClient(client *http.Client) *CustomerGatewayDeleteDocumentParams {
	var ()
	return &CustomerGatewayDeleteDocumentParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayDeleteDocumentParams contains all the parameters to send to the API endpoint
for the customer gateway delete document operation typically these are written to a http.Request
*/
type CustomerGatewayDeleteDocumentParams struct {

	/*CollectionID*/
	CollectionID string
	/*DocumentID*/
	DocumentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) WithTimeout(timeout time.Duration) *CustomerGatewayDeleteDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) WithContext(ctx context.Context) *CustomerGatewayDeleteDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) WithHTTPClient(client *http.Client) *CustomerGatewayDeleteDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionID adds the collectionID to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) WithCollectionID(collectionID string) *CustomerGatewayDeleteDocumentParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WithDocumentID adds the documentID to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) WithDocumentID(documentID string) *CustomerGatewayDeleteDocumentParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the customer gateway delete document params
func (o *CustomerGatewayDeleteDocumentParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayDeleteDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collection_id
	if err := r.SetPathParam("collection_id", o.CollectionID); err != nil {
		return err
	}

	// path param document_id
	if err := r.SetPathParam("document_id", o.DocumentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
