// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerGatewayListNotificationPreferencesParams creates a new CustomerGatewayListNotificationPreferencesParams object
// with the default values initialized.
func NewCustomerGatewayListNotificationPreferencesParams() *CustomerGatewayListNotificationPreferencesParams {

	return &CustomerGatewayListNotificationPreferencesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayListNotificationPreferencesParamsWithTimeout creates a new CustomerGatewayListNotificationPreferencesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayListNotificationPreferencesParamsWithTimeout(timeout time.Duration) *CustomerGatewayListNotificationPreferencesParams {

	return &CustomerGatewayListNotificationPreferencesParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayListNotificationPreferencesParamsWithContext creates a new CustomerGatewayListNotificationPreferencesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayListNotificationPreferencesParamsWithContext(ctx context.Context) *CustomerGatewayListNotificationPreferencesParams {

	return &CustomerGatewayListNotificationPreferencesParams{

		Context: ctx,
	}
}

// NewCustomerGatewayListNotificationPreferencesParamsWithHTTPClient creates a new CustomerGatewayListNotificationPreferencesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayListNotificationPreferencesParamsWithHTTPClient(client *http.Client) *CustomerGatewayListNotificationPreferencesParams {

	return &CustomerGatewayListNotificationPreferencesParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayListNotificationPreferencesParams contains all the parameters to send to the API endpoint
for the customer gateway list notification preferences operation typically these are written to a http.Request
*/
type CustomerGatewayListNotificationPreferencesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway list notification preferences params
func (o *CustomerGatewayListNotificationPreferencesParams) WithTimeout(timeout time.Duration) *CustomerGatewayListNotificationPreferencesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway list notification preferences params
func (o *CustomerGatewayListNotificationPreferencesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway list notification preferences params
func (o *CustomerGatewayListNotificationPreferencesParams) WithContext(ctx context.Context) *CustomerGatewayListNotificationPreferencesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway list notification preferences params
func (o *CustomerGatewayListNotificationPreferencesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway list notification preferences params
func (o *CustomerGatewayListNotificationPreferencesParams) WithHTTPClient(client *http.Client) *CustomerGatewayListNotificationPreferencesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway list notification preferences params
func (o *CustomerGatewayListNotificationPreferencesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayListNotificationPreferencesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
