// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// NewCustomerGatewayCreateDownloadDocumentLinkParams creates a new CustomerGatewayCreateDownloadDocumentLinkParams object
// with the default values initialized.
func NewCustomerGatewayCreateDownloadDocumentLinkParams() *CustomerGatewayCreateDownloadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateDownloadDocumentLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayCreateDownloadDocumentLinkParamsWithTimeout creates a new CustomerGatewayCreateDownloadDocumentLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayCreateDownloadDocumentLinkParamsWithTimeout(timeout time.Duration) *CustomerGatewayCreateDownloadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateDownloadDocumentLinkParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayCreateDownloadDocumentLinkParamsWithContext creates a new CustomerGatewayCreateDownloadDocumentLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayCreateDownloadDocumentLinkParamsWithContext(ctx context.Context) *CustomerGatewayCreateDownloadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateDownloadDocumentLinkParams{

		Context: ctx,
	}
}

// NewCustomerGatewayCreateDownloadDocumentLinkParamsWithHTTPClient creates a new CustomerGatewayCreateDownloadDocumentLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayCreateDownloadDocumentLinkParamsWithHTTPClient(client *http.Client) *CustomerGatewayCreateDownloadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateDownloadDocumentLinkParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayCreateDownloadDocumentLinkParams contains all the parameters to send to the API endpoint
for the customer gateway create download document link operation typically these are written to a http.Request
*/
type CustomerGatewayCreateDownloadDocumentLinkParams struct {

	/*Body*/
	Body *models.V1CreateDownloadDocumentLinkRequest
	/*CollectionID*/
	CollectionID string
	/*DocumentID*/
	DocumentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) WithTimeout(timeout time.Duration) *CustomerGatewayCreateDownloadDocumentLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) WithContext(ctx context.Context) *CustomerGatewayCreateDownloadDocumentLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) WithHTTPClient(client *http.Client) *CustomerGatewayCreateDownloadDocumentLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) WithBody(body *models.V1CreateDownloadDocumentLinkRequest) *CustomerGatewayCreateDownloadDocumentLinkParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) SetBody(body *models.V1CreateDownloadDocumentLinkRequest) {
	o.Body = body
}

// WithCollectionID adds the collectionID to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) WithCollectionID(collectionID string) *CustomerGatewayCreateDownloadDocumentLinkParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WithDocumentID adds the documentID to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) WithDocumentID(documentID string) *CustomerGatewayCreateDownloadDocumentLinkParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the customer gateway create download document link params
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayCreateDownloadDocumentLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param collection_id
	if err := r.SetPathParam("collection_id", o.CollectionID); err != nil {
		return err
	}

	// path param document_id
	if err := r.SetPathParam("document_id", o.DocumentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
