// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerGatewayRemoveEmploymentParams creates a new CustomerGatewayRemoveEmploymentParams object
// with the default values initialized.
func NewCustomerGatewayRemoveEmploymentParams() *CustomerGatewayRemoveEmploymentParams {
	var ()
	return &CustomerGatewayRemoveEmploymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayRemoveEmploymentParamsWithTimeout creates a new CustomerGatewayRemoveEmploymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayRemoveEmploymentParamsWithTimeout(timeout time.Duration) *CustomerGatewayRemoveEmploymentParams {
	var ()
	return &CustomerGatewayRemoveEmploymentParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayRemoveEmploymentParamsWithContext creates a new CustomerGatewayRemoveEmploymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayRemoveEmploymentParamsWithContext(ctx context.Context) *CustomerGatewayRemoveEmploymentParams {
	var ()
	return &CustomerGatewayRemoveEmploymentParams{

		Context: ctx,
	}
}

// NewCustomerGatewayRemoveEmploymentParamsWithHTTPClient creates a new CustomerGatewayRemoveEmploymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayRemoveEmploymentParamsWithHTTPClient(client *http.Client) *CustomerGatewayRemoveEmploymentParams {
	var ()
	return &CustomerGatewayRemoveEmploymentParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayRemoveEmploymentParams contains all the parameters to send to the API endpoint
for the customer gateway remove employment operation typically these are written to a http.Request
*/
type CustomerGatewayRemoveEmploymentParams struct {

	/*EmploymentID*/
	EmploymentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) WithTimeout(timeout time.Duration) *CustomerGatewayRemoveEmploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) WithContext(ctx context.Context) *CustomerGatewayRemoveEmploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) WithHTTPClient(client *http.Client) *CustomerGatewayRemoveEmploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmploymentID adds the employmentID to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) WithEmploymentID(employmentID string) *CustomerGatewayRemoveEmploymentParams {
	o.SetEmploymentID(employmentID)
	return o
}

// SetEmploymentID adds the employmentId to the customer gateway remove employment params
func (o *CustomerGatewayRemoveEmploymentParams) SetEmploymentID(employmentID string) {
	o.EmploymentID = employmentID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayRemoveEmploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param employment_id
	if err := r.SetPathParam("employment_id", o.EmploymentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
