// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// NewCustomerGatewaySetNotificationPreferencesParams creates a new CustomerGatewaySetNotificationPreferencesParams object
// with the default values initialized.
func NewCustomerGatewaySetNotificationPreferencesParams() *CustomerGatewaySetNotificationPreferencesParams {
	var ()
	return &CustomerGatewaySetNotificationPreferencesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewaySetNotificationPreferencesParamsWithTimeout creates a new CustomerGatewaySetNotificationPreferencesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewaySetNotificationPreferencesParamsWithTimeout(timeout time.Duration) *CustomerGatewaySetNotificationPreferencesParams {
	var ()
	return &CustomerGatewaySetNotificationPreferencesParams{

		timeout: timeout,
	}
}

// NewCustomerGatewaySetNotificationPreferencesParamsWithContext creates a new CustomerGatewaySetNotificationPreferencesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewaySetNotificationPreferencesParamsWithContext(ctx context.Context) *CustomerGatewaySetNotificationPreferencesParams {
	var ()
	return &CustomerGatewaySetNotificationPreferencesParams{

		Context: ctx,
	}
}

// NewCustomerGatewaySetNotificationPreferencesParamsWithHTTPClient creates a new CustomerGatewaySetNotificationPreferencesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewaySetNotificationPreferencesParamsWithHTTPClient(client *http.Client) *CustomerGatewaySetNotificationPreferencesParams {
	var ()
	return &CustomerGatewaySetNotificationPreferencesParams{
		HTTPClient: client,
	}
}

/*CustomerGatewaySetNotificationPreferencesParams contains all the parameters to send to the API endpoint
for the customer gateway set notification preferences operation typically these are written to a http.Request
*/
type CustomerGatewaySetNotificationPreferencesParams struct {

	/*Body*/
	Body *models.V1SetNotificationPreferencesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) WithTimeout(timeout time.Duration) *CustomerGatewaySetNotificationPreferencesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) WithContext(ctx context.Context) *CustomerGatewaySetNotificationPreferencesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) WithHTTPClient(client *http.Client) *CustomerGatewaySetNotificationPreferencesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) WithBody(body *models.V1SetNotificationPreferencesRequest) *CustomerGatewaySetNotificationPreferencesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer gateway set notification preferences params
func (o *CustomerGatewaySetNotificationPreferencesParams) SetBody(body *models.V1SetNotificationPreferencesRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewaySetNotificationPreferencesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
