// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayAddCompanyReader is a Reader for the CustomerGatewayAddCompany structure.
type CustomerGatewayAddCompanyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayAddCompanyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayAddCompanyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayAddCompanyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayAddCompanyOK creates a CustomerGatewayAddCompanyOK with default headers values
func NewCustomerGatewayAddCompanyOK() *CustomerGatewayAddCompanyOK {
	return &CustomerGatewayAddCompanyOK{}
}

/*CustomerGatewayAddCompanyOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayAddCompanyOK struct {
	Payload models.V1AddCompanyResponse
}

func (o *CustomerGatewayAddCompanyOK) Error() string {
	return fmt.Sprintf("[POST /v1/companies][%d] customerGatewayAddCompanyOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayAddCompanyOK) GetPayload() models.V1AddCompanyResponse {
	return o.Payload
}

func (o *CustomerGatewayAddCompanyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayAddCompanyDefault creates a CustomerGatewayAddCompanyDefault with default headers values
func NewCustomerGatewayAddCompanyDefault(code int) *CustomerGatewayAddCompanyDefault {
	return &CustomerGatewayAddCompanyDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayAddCompanyDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayAddCompanyDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway add company default response
func (o *CustomerGatewayAddCompanyDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayAddCompanyDefault) Error() string {
	return fmt.Sprintf("[POST /v1/companies][%d] CustomerGateway_AddCompany default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayAddCompanyDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayAddCompanyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
