// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// NewCustomerGatewaySetEmploymentParams creates a new CustomerGatewaySetEmploymentParams object
// with the default values initialized.
func NewCustomerGatewaySetEmploymentParams() *CustomerGatewaySetEmploymentParams {
	var ()
	return &CustomerGatewaySetEmploymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewaySetEmploymentParamsWithTimeout creates a new CustomerGatewaySetEmploymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewaySetEmploymentParamsWithTimeout(timeout time.Duration) *CustomerGatewaySetEmploymentParams {
	var ()
	return &CustomerGatewaySetEmploymentParams{

		timeout: timeout,
	}
}

// NewCustomerGatewaySetEmploymentParamsWithContext creates a new CustomerGatewaySetEmploymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewaySetEmploymentParamsWithContext(ctx context.Context) *CustomerGatewaySetEmploymentParams {
	var ()
	return &CustomerGatewaySetEmploymentParams{

		Context: ctx,
	}
}

// NewCustomerGatewaySetEmploymentParamsWithHTTPClient creates a new CustomerGatewaySetEmploymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewaySetEmploymentParamsWithHTTPClient(client *http.Client) *CustomerGatewaySetEmploymentParams {
	var ()
	return &CustomerGatewaySetEmploymentParams{
		HTTPClient: client,
	}
}

/*CustomerGatewaySetEmploymentParams contains all the parameters to send to the API endpoint
for the customer gateway set employment operation typically these are written to a http.Request
*/
type CustomerGatewaySetEmploymentParams struct {

	/*Body*/
	Body *models.V1SetEmploymentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) WithTimeout(timeout time.Duration) *CustomerGatewaySetEmploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) WithContext(ctx context.Context) *CustomerGatewaySetEmploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) WithHTTPClient(client *http.Client) *CustomerGatewaySetEmploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) WithBody(body *models.V1SetEmploymentRequest) *CustomerGatewaySetEmploymentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer gateway set employment params
func (o *CustomerGatewaySetEmploymentParams) SetBody(body *models.V1SetEmploymentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewaySetEmploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
