// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayListNotificationPreferencesReader is a Reader for the CustomerGatewayListNotificationPreferences structure.
type CustomerGatewayListNotificationPreferencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayListNotificationPreferencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayListNotificationPreferencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayListNotificationPreferencesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayListNotificationPreferencesOK creates a CustomerGatewayListNotificationPreferencesOK with default headers values
func NewCustomerGatewayListNotificationPreferencesOK() *CustomerGatewayListNotificationPreferencesOK {
	return &CustomerGatewayListNotificationPreferencesOK{}
}

/*CustomerGatewayListNotificationPreferencesOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayListNotificationPreferencesOK struct {
	Payload *models.V1ListNotificationPreferencesResponse
}

func (o *CustomerGatewayListNotificationPreferencesOK) Error() string {
	return fmt.Sprintf("[GET /v1/settings/notifications][%d] customerGatewayListNotificationPreferencesOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayListNotificationPreferencesOK) GetPayload() *models.V1ListNotificationPreferencesResponse {
	return o.Payload
}

func (o *CustomerGatewayListNotificationPreferencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ListNotificationPreferencesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayListNotificationPreferencesDefault creates a CustomerGatewayListNotificationPreferencesDefault with default headers values
func NewCustomerGatewayListNotificationPreferencesDefault(code int) *CustomerGatewayListNotificationPreferencesDefault {
	return &CustomerGatewayListNotificationPreferencesDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayListNotificationPreferencesDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayListNotificationPreferencesDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway list notification preferences default response
func (o *CustomerGatewayListNotificationPreferencesDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayListNotificationPreferencesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/settings/notifications][%d] CustomerGateway_ListNotificationPreferences default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayListNotificationPreferencesDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayListNotificationPreferencesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
