// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerGatewayGetNotificationsParams creates a new CustomerGatewayGetNotificationsParams object
// with the default values initialized.
func NewCustomerGatewayGetNotificationsParams() *CustomerGatewayGetNotificationsParams {

	return &CustomerGatewayGetNotificationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayGetNotificationsParamsWithTimeout creates a new CustomerGatewayGetNotificationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayGetNotificationsParamsWithTimeout(timeout time.Duration) *CustomerGatewayGetNotificationsParams {

	return &CustomerGatewayGetNotificationsParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayGetNotificationsParamsWithContext creates a new CustomerGatewayGetNotificationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayGetNotificationsParamsWithContext(ctx context.Context) *CustomerGatewayGetNotificationsParams {

	return &CustomerGatewayGetNotificationsParams{

		Context: ctx,
	}
}

// NewCustomerGatewayGetNotificationsParamsWithHTTPClient creates a new CustomerGatewayGetNotificationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayGetNotificationsParamsWithHTTPClient(client *http.Client) *CustomerGatewayGetNotificationsParams {

	return &CustomerGatewayGetNotificationsParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayGetNotificationsParams contains all the parameters to send to the API endpoint
for the customer gateway get notifications operation typically these are written to a http.Request
*/
type CustomerGatewayGetNotificationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway get notifications params
func (o *CustomerGatewayGetNotificationsParams) WithTimeout(timeout time.Duration) *CustomerGatewayGetNotificationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway get notifications params
func (o *CustomerGatewayGetNotificationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway get notifications params
func (o *CustomerGatewayGetNotificationsParams) WithContext(ctx context.Context) *CustomerGatewayGetNotificationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway get notifications params
func (o *CustomerGatewayGetNotificationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway get notifications params
func (o *CustomerGatewayGetNotificationsParams) WithHTTPClient(client *http.Client) *CustomerGatewayGetNotificationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway get notifications params
func (o *CustomerGatewayGetNotificationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayGetNotificationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
