// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// NewCustomerGatewayCreateUploadDocumentLinkParams creates a new CustomerGatewayCreateUploadDocumentLinkParams object
// with the default values initialized.
func NewCustomerGatewayCreateUploadDocumentLinkParams() *CustomerGatewayCreateUploadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateUploadDocumentLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayCreateUploadDocumentLinkParamsWithTimeout creates a new CustomerGatewayCreateUploadDocumentLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayCreateUploadDocumentLinkParamsWithTimeout(timeout time.Duration) *CustomerGatewayCreateUploadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateUploadDocumentLinkParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayCreateUploadDocumentLinkParamsWithContext creates a new CustomerGatewayCreateUploadDocumentLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayCreateUploadDocumentLinkParamsWithContext(ctx context.Context) *CustomerGatewayCreateUploadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateUploadDocumentLinkParams{

		Context: ctx,
	}
}

// NewCustomerGatewayCreateUploadDocumentLinkParamsWithHTTPClient creates a new CustomerGatewayCreateUploadDocumentLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayCreateUploadDocumentLinkParamsWithHTTPClient(client *http.Client) *CustomerGatewayCreateUploadDocumentLinkParams {
	var ()
	return &CustomerGatewayCreateUploadDocumentLinkParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayCreateUploadDocumentLinkParams contains all the parameters to send to the API endpoint
for the customer gateway create upload document link operation typically these are written to a http.Request
*/
type CustomerGatewayCreateUploadDocumentLinkParams struct {

	/*Body*/
	Body *models.V1CreateUploadDocumentLinkRequest
	/*CollectionID*/
	CollectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) WithTimeout(timeout time.Duration) *CustomerGatewayCreateUploadDocumentLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) WithContext(ctx context.Context) *CustomerGatewayCreateUploadDocumentLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) WithHTTPClient(client *http.Client) *CustomerGatewayCreateUploadDocumentLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) WithBody(body *models.V1CreateUploadDocumentLinkRequest) *CustomerGatewayCreateUploadDocumentLinkParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) SetBody(body *models.V1CreateUploadDocumentLinkRequest) {
	o.Body = body
}

// WithCollectionID adds the collectionID to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) WithCollectionID(collectionID string) *CustomerGatewayCreateUploadDocumentLinkParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the customer gateway create upload document link params
func (o *CustomerGatewayCreateUploadDocumentLinkParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayCreateUploadDocumentLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param collection_id
	if err := r.SetPathParam("collection_id", o.CollectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
