// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayGetAddressHistoryReader is a Reader for the CustomerGatewayGetAddressHistory structure.
type CustomerGatewayGetAddressHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayGetAddressHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayGetAddressHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayGetAddressHistoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayGetAddressHistoryOK creates a CustomerGatewayGetAddressHistoryOK with default headers values
func NewCustomerGatewayGetAddressHistoryOK() *CustomerGatewayGetAddressHistoryOK {
	return &CustomerGatewayGetAddressHistoryOK{}
}

/*CustomerGatewayGetAddressHistoryOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayGetAddressHistoryOK struct {
	Payload *models.V1GetAddressHistoryResponse
}

func (o *CustomerGatewayGetAddressHistoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/addresses][%d] customerGatewayGetAddressHistoryOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayGetAddressHistoryOK) GetPayload() *models.V1GetAddressHistoryResponse {
	return o.Payload
}

func (o *CustomerGatewayGetAddressHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetAddressHistoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayGetAddressHistoryDefault creates a CustomerGatewayGetAddressHistoryDefault with default headers values
func NewCustomerGatewayGetAddressHistoryDefault(code int) *CustomerGatewayGetAddressHistoryDefault {
	return &CustomerGatewayGetAddressHistoryDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayGetAddressHistoryDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayGetAddressHistoryDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway get address history default response
func (o *CustomerGatewayGetAddressHistoryDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayGetAddressHistoryDefault) Error() string {
	return fmt.Sprintf("[GET /v1/addresses][%d] CustomerGateway_GetAddressHistory default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayGetAddressHistoryDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayGetAddressHistoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
