// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayListDocumentsReader is a Reader for the CustomerGatewayListDocuments structure.
type CustomerGatewayListDocumentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayListDocumentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayListDocumentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayListDocumentsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayListDocumentsOK creates a CustomerGatewayListDocumentsOK with default headers values
func NewCustomerGatewayListDocumentsOK() *CustomerGatewayListDocumentsOK {
	return &CustomerGatewayListDocumentsOK{}
}

/*CustomerGatewayListDocumentsOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayListDocumentsOK struct {
	Payload *models.V1ListDocumentsResponse
}

func (o *CustomerGatewayListDocumentsOK) Error() string {
	return fmt.Sprintf("[GET /v1/documents][%d] customerGatewayListDocumentsOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayListDocumentsOK) GetPayload() *models.V1ListDocumentsResponse {
	return o.Payload
}

func (o *CustomerGatewayListDocumentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ListDocumentsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayListDocumentsDefault creates a CustomerGatewayListDocumentsDefault with default headers values
func NewCustomerGatewayListDocumentsDefault(code int) *CustomerGatewayListDocumentsDefault {
	return &CustomerGatewayListDocumentsDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayListDocumentsDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayListDocumentsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway list documents default response
func (o *CustomerGatewayListDocumentsDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayListDocumentsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/documents][%d] CustomerGateway_ListDocuments default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayListDocumentsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayListDocumentsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
