// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerGatewayGetEmploymentParams creates a new CustomerGatewayGetEmploymentParams object
// with the default values initialized.
func NewCustomerGatewayGetEmploymentParams() *CustomerGatewayGetEmploymentParams {

	return &CustomerGatewayGetEmploymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerGatewayGetEmploymentParamsWithTimeout creates a new CustomerGatewayGetEmploymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerGatewayGetEmploymentParamsWithTimeout(timeout time.Duration) *CustomerGatewayGetEmploymentParams {

	return &CustomerGatewayGetEmploymentParams{

		timeout: timeout,
	}
}

// NewCustomerGatewayGetEmploymentParamsWithContext creates a new CustomerGatewayGetEmploymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerGatewayGetEmploymentParamsWithContext(ctx context.Context) *CustomerGatewayGetEmploymentParams {

	return &CustomerGatewayGetEmploymentParams{

		Context: ctx,
	}
}

// NewCustomerGatewayGetEmploymentParamsWithHTTPClient creates a new CustomerGatewayGetEmploymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomerGatewayGetEmploymentParamsWithHTTPClient(client *http.Client) *CustomerGatewayGetEmploymentParams {

	return &CustomerGatewayGetEmploymentParams{
		HTTPClient: client,
	}
}

/*CustomerGatewayGetEmploymentParams contains all the parameters to send to the API endpoint
for the customer gateway get employment operation typically these are written to a http.Request
*/
type CustomerGatewayGetEmploymentParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer gateway get employment params
func (o *CustomerGatewayGetEmploymentParams) WithTimeout(timeout time.Duration) *CustomerGatewayGetEmploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer gateway get employment params
func (o *CustomerGatewayGetEmploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer gateway get employment params
func (o *CustomerGatewayGetEmploymentParams) WithContext(ctx context.Context) *CustomerGatewayGetEmploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer gateway get employment params
func (o *CustomerGatewayGetEmploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer gateway get employment params
func (o *CustomerGatewayGetEmploymentParams) WithHTTPClient(client *http.Client) *CustomerGatewayGetEmploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer gateway get employment params
func (o *CustomerGatewayGetEmploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerGatewayGetEmploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
