// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayDeleteDocumentReader is a Reader for the CustomerGatewayDeleteDocument structure.
type CustomerGatewayDeleteDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayDeleteDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayDeleteDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayDeleteDocumentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayDeleteDocumentOK creates a CustomerGatewayDeleteDocumentOK with default headers values
func NewCustomerGatewayDeleteDocumentOK() *CustomerGatewayDeleteDocumentOK {
	return &CustomerGatewayDeleteDocumentOK{}
}

/*CustomerGatewayDeleteDocumentOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayDeleteDocumentOK struct {
	Payload models.V1DeleteDocumentResponse
}

func (o *CustomerGatewayDeleteDocumentOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/documents/{collection_id}/{document_id}][%d] customerGatewayDeleteDocumentOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayDeleteDocumentOK) GetPayload() models.V1DeleteDocumentResponse {
	return o.Payload
}

func (o *CustomerGatewayDeleteDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayDeleteDocumentDefault creates a CustomerGatewayDeleteDocumentDefault with default headers values
func NewCustomerGatewayDeleteDocumentDefault(code int) *CustomerGatewayDeleteDocumentDefault {
	return &CustomerGatewayDeleteDocumentDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayDeleteDocumentDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayDeleteDocumentDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway delete document default response
func (o *CustomerGatewayDeleteDocumentDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayDeleteDocumentDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/documents/{collection_id}/{document_id}][%d] CustomerGateway_DeleteDocument default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayDeleteDocumentDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayDeleteDocumentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
