// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayCreateDownloadDocumentLinkReader is a Reader for the CustomerGatewayCreateDownloadDocumentLink structure.
type CustomerGatewayCreateDownloadDocumentLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayCreateDownloadDocumentLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayCreateDownloadDocumentLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayCreateDownloadDocumentLinkDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayCreateDownloadDocumentLinkOK creates a CustomerGatewayCreateDownloadDocumentLinkOK with default headers values
func NewCustomerGatewayCreateDownloadDocumentLinkOK() *CustomerGatewayCreateDownloadDocumentLinkOK {
	return &CustomerGatewayCreateDownloadDocumentLinkOK{}
}

/*CustomerGatewayCreateDownloadDocumentLinkOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayCreateDownloadDocumentLinkOK struct {
	Payload *models.V1CreateDownloadDocumentLinkResponse
}

func (o *CustomerGatewayCreateDownloadDocumentLinkOK) Error() string {
	return fmt.Sprintf("[POST /v1/documents/{collection_id}/{document_id}][%d] customerGatewayCreateDownloadDocumentLinkOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayCreateDownloadDocumentLinkOK) GetPayload() *models.V1CreateDownloadDocumentLinkResponse {
	return o.Payload
}

func (o *CustomerGatewayCreateDownloadDocumentLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1CreateDownloadDocumentLinkResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayCreateDownloadDocumentLinkDefault creates a CustomerGatewayCreateDownloadDocumentLinkDefault with default headers values
func NewCustomerGatewayCreateDownloadDocumentLinkDefault(code int) *CustomerGatewayCreateDownloadDocumentLinkDefault {
	return &CustomerGatewayCreateDownloadDocumentLinkDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayCreateDownloadDocumentLinkDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayCreateDownloadDocumentLinkDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway create download document link default response
func (o *CustomerGatewayCreateDownloadDocumentLinkDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayCreateDownloadDocumentLinkDefault) Error() string {
	return fmt.Sprintf("[POST /v1/documents/{collection_id}/{document_id}][%d] CustomerGateway_CreateDownloadDocumentLink default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayCreateDownloadDocumentLinkDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayCreateDownloadDocumentLinkDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
