// Code generated by go-swagger; DO NOT EDIT.

package customer_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/customers/models"
)

// CustomerGatewayCreateUploadDocumentLinkReader is a Reader for the CustomerGatewayCreateUploadDocumentLink structure.
type CustomerGatewayCreateUploadDocumentLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerGatewayCreateUploadDocumentLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerGatewayCreateUploadDocumentLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerGatewayCreateUploadDocumentLinkDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerGatewayCreateUploadDocumentLinkOK creates a CustomerGatewayCreateUploadDocumentLinkOK with default headers values
func NewCustomerGatewayCreateUploadDocumentLinkOK() *CustomerGatewayCreateUploadDocumentLinkOK {
	return &CustomerGatewayCreateUploadDocumentLinkOK{}
}

/*CustomerGatewayCreateUploadDocumentLinkOK handles this case with default header values.

A successful response.
*/
type CustomerGatewayCreateUploadDocumentLinkOK struct {
	Payload *models.V1CreateUploadDocumentLinkResponse
}

func (o *CustomerGatewayCreateUploadDocumentLinkOK) Error() string {
	return fmt.Sprintf("[POST /v1/documents/{collection_id}][%d] customerGatewayCreateUploadDocumentLinkOK  %+v", 200, o.Payload)
}

func (o *CustomerGatewayCreateUploadDocumentLinkOK) GetPayload() *models.V1CreateUploadDocumentLinkResponse {
	return o.Payload
}

func (o *CustomerGatewayCreateUploadDocumentLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1CreateUploadDocumentLinkResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerGatewayCreateUploadDocumentLinkDefault creates a CustomerGatewayCreateUploadDocumentLinkDefault with default headers values
func NewCustomerGatewayCreateUploadDocumentLinkDefault(code int) *CustomerGatewayCreateUploadDocumentLinkDefault {
	return &CustomerGatewayCreateUploadDocumentLinkDefault{
		_statusCode: code,
	}
}

/*CustomerGatewayCreateUploadDocumentLinkDefault handles this case with default header values.

An unexpected error response
*/
type CustomerGatewayCreateUploadDocumentLinkDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the customer gateway create upload document link default response
func (o *CustomerGatewayCreateUploadDocumentLinkDefault) Code() int {
	return o._statusCode
}

func (o *CustomerGatewayCreateUploadDocumentLinkDefault) Error() string {
	return fmt.Sprintf("[POST /v1/documents/{collection_id}][%d] CustomerGateway_CreateUploadDocumentLink default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerGatewayCreateUploadDocumentLinkDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CustomerGatewayCreateUploadDocumentLinkDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
