// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identities/models"
)

// IdentitiesDoResetPasswordReader is a Reader for the IdentitiesDoResetPassword structure.
type IdentitiesDoResetPasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesDoResetPasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesDoResetPasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesDoResetPasswordDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesDoResetPasswordOK creates a IdentitiesDoResetPasswordOK with default headers values
func NewIdentitiesDoResetPasswordOK() *IdentitiesDoResetPasswordOK {
	return &IdentitiesDoResetPasswordOK{}
}

/*IdentitiesDoResetPasswordOK handles this case with default header values.

A successful response.
*/
type IdentitiesDoResetPasswordOK struct {
	Payload models.V1DoResetPasswordResponse
}

func (o *IdentitiesDoResetPasswordOK) Error() string {
	return fmt.Sprintf("[POST /v1/users/reset][%d] identitiesDoResetPasswordOK  %+v", 200, o.Payload)
}

func (o *IdentitiesDoResetPasswordOK) GetPayload() models.V1DoResetPasswordResponse {
	return o.Payload
}

func (o *IdentitiesDoResetPasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesDoResetPasswordDefault creates a IdentitiesDoResetPasswordDefault with default headers values
func NewIdentitiesDoResetPasswordDefault(code int) *IdentitiesDoResetPasswordDefault {
	return &IdentitiesDoResetPasswordDefault{
		_statusCode: code,
	}
}

/*IdentitiesDoResetPasswordDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesDoResetPasswordDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities do reset password default response
func (o *IdentitiesDoResetPasswordDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesDoResetPasswordDefault) Error() string {
	return fmt.Sprintf("[POST /v1/users/reset][%d] Identities_DoResetPassword default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesDoResetPasswordDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesDoResetPasswordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
