// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identities/models"
)

// NewIdentitiesAddOrganisationMemberParams creates a new IdentitiesAddOrganisationMemberParams object
// with the default values initialized.
func NewIdentitiesAddOrganisationMemberParams() *IdentitiesAddOrganisationMemberParams {
	var ()
	return &IdentitiesAddOrganisationMemberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIdentitiesAddOrganisationMemberParamsWithTimeout creates a new IdentitiesAddOrganisationMemberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIdentitiesAddOrganisationMemberParamsWithTimeout(timeout time.Duration) *IdentitiesAddOrganisationMemberParams {
	var ()
	return &IdentitiesAddOrganisationMemberParams{

		timeout: timeout,
	}
}

// NewIdentitiesAddOrganisationMemberParamsWithContext creates a new IdentitiesAddOrganisationMemberParams object
// with the default values initialized, and the ability to set a context for a request
func NewIdentitiesAddOrganisationMemberParamsWithContext(ctx context.Context) *IdentitiesAddOrganisationMemberParams {
	var ()
	return &IdentitiesAddOrganisationMemberParams{

		Context: ctx,
	}
}

// NewIdentitiesAddOrganisationMemberParamsWithHTTPClient creates a new IdentitiesAddOrganisationMemberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIdentitiesAddOrganisationMemberParamsWithHTTPClient(client *http.Client) *IdentitiesAddOrganisationMemberParams {
	var ()
	return &IdentitiesAddOrganisationMemberParams{
		HTTPClient: client,
	}
}

/*IdentitiesAddOrganisationMemberParams contains all the parameters to send to the API endpoint
for the identities add organisation member operation typically these are written to a http.Request
*/
type IdentitiesAddOrganisationMemberParams struct {

	/*Body*/
	Body *models.V1AddOrganisationMemberRequest
	/*OrganisationID*/
	OrganisationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) WithTimeout(timeout time.Duration) *IdentitiesAddOrganisationMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) WithContext(ctx context.Context) *IdentitiesAddOrganisationMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) WithHTTPClient(client *http.Client) *IdentitiesAddOrganisationMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) WithBody(body *models.V1AddOrganisationMemberRequest) *IdentitiesAddOrganisationMemberParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) SetBody(body *models.V1AddOrganisationMemberRequest) {
	o.Body = body
}

// WithOrganisationID adds the organisationID to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) WithOrganisationID(organisationID string) *IdentitiesAddOrganisationMemberParams {
	o.SetOrganisationID(organisationID)
	return o
}

// SetOrganisationID adds the organisationId to the identities add organisation member params
func (o *IdentitiesAddOrganisationMemberParams) SetOrganisationID(organisationID string) {
	o.OrganisationID = organisationID
}

// WriteToRequest writes these params to a swagger request
func (o *IdentitiesAddOrganisationMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param organisation_id
	if err := r.SetPathParam("organisation_id", o.OrganisationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
