// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identities/models"
)

// IdentitiesAddOrganisationMemberReader is a Reader for the IdentitiesAddOrganisationMember structure.
type IdentitiesAddOrganisationMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesAddOrganisationMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesAddOrganisationMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesAddOrganisationMemberDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesAddOrganisationMemberOK creates a IdentitiesAddOrganisationMemberOK with default headers values
func NewIdentitiesAddOrganisationMemberOK() *IdentitiesAddOrganisationMemberOK {
	return &IdentitiesAddOrganisationMemberOK{}
}

/*IdentitiesAddOrganisationMemberOK handles this case with default header values.

A successful response.
*/
type IdentitiesAddOrganisationMemberOK struct {
	Payload models.V1AddOrganisationMemberResponse
}

func (o *IdentitiesAddOrganisationMemberOK) Error() string {
	return fmt.Sprintf("[POST /v1/organisations/{organisation_id}/members][%d] identitiesAddOrganisationMemberOK  %+v", 200, o.Payload)
}

func (o *IdentitiesAddOrganisationMemberOK) GetPayload() models.V1AddOrganisationMemberResponse {
	return o.Payload
}

func (o *IdentitiesAddOrganisationMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesAddOrganisationMemberDefault creates a IdentitiesAddOrganisationMemberDefault with default headers values
func NewIdentitiesAddOrganisationMemberDefault(code int) *IdentitiesAddOrganisationMemberDefault {
	return &IdentitiesAddOrganisationMemberDefault{
		_statusCode: code,
	}
}

/*IdentitiesAddOrganisationMemberDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesAddOrganisationMemberDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities add organisation member default response
func (o *IdentitiesAddOrganisationMemberDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesAddOrganisationMemberDefault) Error() string {
	return fmt.Sprintf("[POST /v1/organisations/{organisation_id}/members][%d] Identities_AddOrganisationMember default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesAddOrganisationMemberDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesAddOrganisationMemberDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
