// Code generated by go-swagger; DO NOT EDIT.

package identities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"lwebco.de/cosmic-apis-spec/identities/models"
)

// IdentitiesQueryAccountMembershipsReader is a Reader for the IdentitiesQueryAccountMemberships structure.
type IdentitiesQueryAccountMembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentitiesQueryAccountMembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentitiesQueryAccountMembershipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIdentitiesQueryAccountMembershipsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentitiesQueryAccountMembershipsOK creates a IdentitiesQueryAccountMembershipsOK with default headers values
func NewIdentitiesQueryAccountMembershipsOK() *IdentitiesQueryAccountMembershipsOK {
	return &IdentitiesQueryAccountMembershipsOK{}
}

/*IdentitiesQueryAccountMembershipsOK handles this case with default header values.

A successful response.
*/
type IdentitiesQueryAccountMembershipsOK struct {
	Payload *models.V1QueryAccountMembershipsResponse
}

func (o *IdentitiesQueryAccountMembershipsOK) Error() string {
	return fmt.Sprintf("[GET /v1/orgmemberships][%d] identitiesQueryAccountMembershipsOK  %+v", 200, o.Payload)
}

func (o *IdentitiesQueryAccountMembershipsOK) GetPayload() *models.V1QueryAccountMembershipsResponse {
	return o.Payload
}

func (o *IdentitiesQueryAccountMembershipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1QueryAccountMembershipsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentitiesQueryAccountMembershipsDefault creates a IdentitiesQueryAccountMembershipsDefault with default headers values
func NewIdentitiesQueryAccountMembershipsDefault(code int) *IdentitiesQueryAccountMembershipsDefault {
	return &IdentitiesQueryAccountMembershipsDefault{
		_statusCode: code,
	}
}

/*IdentitiesQueryAccountMembershipsDefault handles this case with default header values.

An unexpected error response
*/
type IdentitiesQueryAccountMembershipsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the identities query account memberships default response
func (o *IdentitiesQueryAccountMembershipsDefault) Code() int {
	return o._statusCode
}

func (o *IdentitiesQueryAccountMembershipsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/orgmemberships][%d] Identities_QueryAccountMemberships default  %+v", o._statusCode, o.Payload)
}

func (o *IdentitiesQueryAccountMembershipsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IdentitiesQueryAccountMembershipsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
