// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1AddOrganisationMemberResponse v1 add organisation member response
// swagger:model v1AddOrganisationMemberResponse
type V1AddOrganisationMemberResponse interface{}
