// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateAccountRequest v1 create account request
// swagger:model v1CreateAccountRequest
type V1CreateAccountRequest struct {

	// account id
	AccountID string `json:"account_id,omitempty"`

	// email address
	EmailAddress string `json:"email_address,omitempty"`

	// forename
	Forename string `json:"forename,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// phone number
	PhoneNumber string `json:"phone_number,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// surname
	Surname string `json:"surname,omitempty"`
}

// Validate validates this v1 create account request
func (m *V1CreateAccountRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateAccountRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
