// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1DoResetPasswordRequest v1 do reset password request
// swagger:model v1DoResetPasswordRequest
type V1DoResetPasswordRequest struct {

	// email address
	EmailAddress string `json:"email_address,omitempty"`

	// new password
	NewPassword string `json:"new_password,omitempty"`

	// verification
	Verification string `json:"verification,omitempty"`
}

// Validate validates this v1 do reset password request
func (m *V1DoResetPasswordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DoResetPasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DoResetPasswordRequest) UnmarshalBinary(b []byte) error {
	var res V1DoResetPasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
