// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1LoginRequest v1 login request
// swagger:model v1LoginRequest
type V1LoginRequest struct {

	// email address
	EmailAddress string `json:"email_address,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this v1 login request
func (m *V1LoginRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1LoginRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1LoginRequest) UnmarshalBinary(b []byte) error {
	var res V1LoginRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
