// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1LoginResponse v1 login response
// swagger:model v1LoginResponse
type V1LoginResponse struct {

	// account id
	AccountID string `json:"account_id,omitempty"`

	// email address
	EmailAddress string `json:"email_address,omitempty"`

	// expires
	Expires int32 `json:"expires,omitempty"`

	// organisation id
	OrganisationID string `json:"organisation_id,omitempty"`

	// organisation role
	OrganisationRole string `json:"organisation_role,omitempty"`

	// renew token
	RenewToken string `json:"renew_token,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this v1 login response
func (m *V1LoginResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1LoginResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1LoginResponse) UnmarshalBinary(b []byte) error {
	var res V1LoginResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
