// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TokenCheckResponse v1 token check response
// swagger:model v1TokenCheckResponse
type V1TokenCheckResponse struct {

	// account id
	AccountID string `json:"account_id,omitempty"`

	// email address
	EmailAddress string `json:"email_address,omitempty"`

	// organisation id
	OrganisationID string `json:"organisation_id,omitempty"`

	// organisation role
	OrganisationRole string `json:"organisation_role,omitempty"`
}

// Validate validates this v1 token check response
func (m *V1TokenCheckResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TokenCheckResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TokenCheckResponse) UnmarshalBinary(b []byte) error {
	var res V1TokenCheckResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
