// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryAccountMembershipsResponseMap query account memberships response map
// swagger:model QueryAccountMembershipsResponseMap
type QueryAccountMembershipsResponseMap struct {

	// organisation id
	OrganisationID string `json:"organisation_id,omitempty"`

	// role
	Role V1MemberRole `json:"role,omitempty"`
}

// Validate validates this query account memberships response map
func (m *QueryAccountMembershipsResponseMap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryAccountMembershipsResponseMap) validateRole(formats strfmt.Registry) error {

	if swag.IsZero(m.Role) { // not required
		return nil
	}

	if err := m.Role.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("role")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QueryAccountMembershipsResponseMap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryAccountMembershipsResponseMap) UnmarshalBinary(b []byte) error {
	var res QueryAccountMembershipsResponseMap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
