// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateIntroducerRequest v1 create introducer request
// swagger:model v1CreateIntroducerRequest
type V1CreateIntroducerRequest struct {

	// introducer id
	IntroducerID string `json:"introducer_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organisation id
	OrganisationID string `json:"organisation_id,omitempty"`
}

// Validate validates this v1 create introducer request
func (m *V1CreateIntroducerRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateIntroducerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateIntroducerRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateIntroducerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
