// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1UpdateIntroducerAddressResponse v1 update introducer address response
// swagger:model v1UpdateIntroducerAddressResponse
type V1UpdateIntroducerAddressResponse interface{}
