// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SetOrganisationStatusRequest v1 set organisation status request
// swagger:model v1SetOrganisationStatusRequest
type V1SetOrganisationStatusRequest struct {

	// new status
	NewStatus V1OrganisationStatus `json:"new_status,omitempty"`

	// organisation id
	OrganisationID string `json:"organisation_id,omitempty"`
}

// Validate validates this v1 set organisation status request
func (m *V1SetOrganisationStatusRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SetOrganisationStatusRequest) validateNewStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.NewStatus) { // not required
		return nil
	}

	if err := m.NewStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("new_status")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1SetOrganisationStatusRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SetOrganisationStatusRequest) UnmarshalBinary(b []byte) error {
	var res V1SetOrganisationStatusRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
