// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1SendResetPasswordResponse v1 send reset password response
// swagger:model v1SendResetPasswordResponse
type V1SendResetPasswordResponse interface{}
