// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TokenCheckResponseOrganisationAccess v1 token check response organisation access
// swagger:model v1TokenCheckResponseOrganisationAccess
type V1TokenCheckResponseOrganisationAccess struct {

	// organisation id
	OrganisationID string `json:"organisation_id,omitempty"`

	// role
	Role string `json:"role,omitempty"`
}

// Validate validates this v1 token check response organisation access
func (m *V1TokenCheckResponseOrganisationAccess) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TokenCheckResponseOrganisationAccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TokenCheckResponseOrganisationAccess) UnmarshalBinary(b []byte) error {
	var res V1TokenCheckResponseOrganisationAccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
