// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1TokenRevokeResponse v1 token revoke response
// swagger:model v1TokenRevokeResponse
type V1TokenRevokeResponse interface{}
