// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1UpdateAccountDetailsResponse v1 update account details response
// swagger:model v1UpdateAccountDetailsResponse
type V1UpdateAccountDetailsResponse interface{}
